<?xml version="1.0" encoding="utf-8"?><Database Name="PIAR" Class="GeneralModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ESCRITORIO-CARL\SQLSERVEREXPRESS;Initial Catalog=PIAR;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PIARConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sede" Member="Sede">
    <Type Name="Sede">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Eliminado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Departamento" Member="Departamento">
    <Type Name="Departamento">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodDepartamento" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="NomDepartamento" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Departamento_Municipio" Member="Municipio" ThisKey="CodDepartamento" OtherKey="CodDepartamento" Type="Municipio" />
    </Type>
  </Table>
  <Table Name="dbo.Municipio" Member="Municipio">
    <Type Name="Municipio">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodDepartamento" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CodMunicipio" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NomMunicipio" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Departamento_Municipio" Member="Departamento" ThisKey="CodDepartamento" OtherKey="CodDepartamento" Type="Departamento" IsForeignKey="true" />
    </Type>
  </Table>
</Database>