#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEducativo.Models.Estudiante
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PIAR")]
	public partial class ModelEstudianteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEstudiante(Estudiante instance);
    partial void UpdateEstudiante(Estudiante instance);
    partial void DeleteEstudiante(Estudiante instance);
    #endregion
		
		public ModelEstudianteDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PIARConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelEstudianteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelEstudianteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelEstudianteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelEstudianteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Estudiante> Estudiante
		{
			get
			{
				return this.GetTable<Estudiante>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estudiante")]
	public partial class Estudiante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _TipoDocumentoIdentidad;
		
		private string _DocumentoIdentidad;
		
		private string _PrimerApellido;
		
		private string _SegundoApellido;
		
		private string _PrimerNombre;
		
		private string _SegundoNombre;
		
		private string _Genero;
		
		private System.DateTime _FechaNacimiento;
		
		private string _DepartamentoNacimiento;
		
		private string _MunicipioNacimiento;
		
		private string _DepartamentoDomicilio;
		
		private string _MunicipioDomicilio;
		
		private string _Direccion;
		
		private string _BarrioVereda;
		
		private string _Telefono;
		
		private string _CorreoElectronico;
		
		private System.Nullable<bool> _ModalidadProteccion;
		
		private string _ModalidadProtecciónCual;
		
		private string _Ocupacion;
		
		private System.Nullable<bool> _GrupoEtnico;
		
		private string _GrupoEtnicoCual;
		
		private System.Nullable<bool> _VictimaConflictoArmado;
		
		private System.Nullable<bool> _VictimaConflictoArmadoCertificado;
		
		private System.Nullable<bool> _Discapacidad;
		
		private System.Nullable<bool> _DiscapacidadCertificado;
		
		private System.Nullable<bool> _RegistroCaracterizacionDiscapacidad;
		
		private string _AfiliacionSistemaSalud;
		
		private string _EPS;
		
		private System.Nullable<bool> _AtendidoSalud;
		
		private string _AtendidoSaludCual;
		
		private System.Nullable<int> _AtendidoSaludFrecuencia;
		
		private System.Nullable<bool> _DiagnosticoMedico;
		
		private string _DiagnosticoMedicoCual;
		
		private System.Nullable<bool> _TerapiaMedica;
		
		private string _TerapiaMedicaCual;
		
		private System.Nullable<int> _TerapiaMedicaFrecuencia;
		
		private System.Nullable<bool> _RecibeTratamientoMedico;
		
		private string _RecibeTratamientoMedicoCual;
		
		private System.Nullable<bool> _ConsumeMedicamento;
		
		private System.Nullable<int> _ConsumeMedicamentoFrecuencia;
		
		private string _ConsumeMedicamentoHorario;
		
		private string _NombreMedicamento;
		
		private string _ConsumeMedicamentoHorarioClase;
		
		private System.Nullable<bool> _ElementoApoyo;
		
		private string _ElementoApoyoCual;
		
		private System.Nullable<bool> _DependenciaPersona;
		
		private string _DependenciaPersonaQuien;
		
		private string _DependenciaPersonaNivelEducativo;
		
		private System.Nullable<bool> _PersonaCargo;
		
		private string _PersonaCargoQuien;
		
		private System.Nullable<bool> _PersonaCuidadora;
		
		private string _PersonaCuidadoraNombre;
		
		private string _PersonaCuidadoraParentesco;
		
		private string _PersonaCuidadoraNivelEducativo;
		
		private string _PersonaCuidadoraTelefono;
		
		private string _PersonaCuidadoraEmail;
		
		private string _NombrePersonaCrianza;
		
		private System.Nullable<bool> _RecibeSubsidio;
		
		private string _RecibeSubsidioCual;
		
		private System.Nullable<bool> _MatriculadoInstitucionAnterior;
		
		private string _MatriculadoInstitucionAnteriorCual;
		
		private string _MatriculadoInstitucionAnteriorPorque;
		
		private System.Nullable<int> _CuantoSinEstudiar;
		
		private string _QueAprendio;
		
		private string _UltimoGrado;
		
		private System.Nullable<bool> _Aprobo;
		
		private string _ObservacionCambio;
		
		private string _RazonNoEstudio;
		
		private System.Nullable<bool> _ProgramaComplementario;
		
		private string _ProgramaComplementarioCual;
		
		private int _IdInstitucion;
		
		private int _IdSede;
		
		private string _Jornada;
		
		private string _MedioTransporte;
		
		private string _Grado;
		
		private string _DepartamentoDiligencia;
		
		private string _MunicipioDiligencia;
		
		private string _NombreApellidoDiligencia;
		
		private string _RolDiligencia;
		
		private System.Nullable<System.DateTime> _FechaDiligencia;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private bool _Eliminado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnTipoDocumentoIdentidadChanging(string value);
    partial void OnTipoDocumentoIdentidadChanged();
    partial void OnDocumentoIdentidadChanging(string value);
    partial void OnDocumentoIdentidadChanged();
    partial void OnPrimerApellidoChanging(string value);
    partial void OnPrimerApellidoChanged();
    partial void OnSegundoApellidoChanging(string value);
    partial void OnSegundoApellidoChanged();
    partial void OnPrimerNombreChanging(string value);
    partial void OnPrimerNombreChanged();
    partial void OnSegundoNombreChanging(string value);
    partial void OnSegundoNombreChanged();
    partial void OnGeneroChanging(string value);
    partial void OnGeneroChanged();
    partial void OnFechaNacimientoChanging(System.DateTime value);
    partial void OnFechaNacimientoChanged();
    partial void OnDepartamentoNacimientoChanging(string value);
    partial void OnDepartamentoNacimientoChanged();
    partial void OnMunicipioNacimientoChanging(string value);
    partial void OnMunicipioNacimientoChanged();
    partial void OnDepartamentoDomicilioChanging(string value);
    partial void OnDepartamentoDomicilioChanged();
    partial void OnMunicipioDomicilioChanging(string value);
    partial void OnMunicipioDomicilioChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnBarrioVeredaChanging(string value);
    partial void OnBarrioVeredaChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCorreoElectronicoChanging(string value);
    partial void OnCorreoElectronicoChanged();
    partial void OnModalidadProteccionChanging(System.Nullable<bool> value);
    partial void OnModalidadProteccionChanged();
    partial void OnModalidadProtecciónCualChanging(string value);
    partial void OnModalidadProtecciónCualChanged();
    partial void OnOcupacionChanging(string value);
    partial void OnOcupacionChanged();
    partial void OnGrupoEtnicoChanging(System.Nullable<bool> value);
    partial void OnGrupoEtnicoChanged();
    partial void OnGrupoEtnicoCualChanging(string value);
    partial void OnGrupoEtnicoCualChanged();
    partial void OnVictimaConflictoArmadoChanging(System.Nullable<bool> value);
    partial void OnVictimaConflictoArmadoChanged();
    partial void OnVictimaConflictoArmadoCertificadoChanging(System.Nullable<bool> value);
    partial void OnVictimaConflictoArmadoCertificadoChanged();
    partial void OnDiscapacidadChanging(System.Nullable<bool> value);
    partial void OnDiscapacidadChanged();
    partial void OnDiscapacidadCertificadoChanging(System.Nullable<bool> value);
    partial void OnDiscapacidadCertificadoChanged();
    partial void OnRegistroCaracterizacionDiscapacidadChanging(System.Nullable<bool> value);
    partial void OnRegistroCaracterizacionDiscapacidadChanged();
    partial void OnAfiliacionSistemaSaludChanging(string value);
    partial void OnAfiliacionSistemaSaludChanged();
    partial void OnEPSChanging(string value);
    partial void OnEPSChanged();
    partial void OnAtendidoSaludChanging(System.Nullable<bool> value);
    partial void OnAtendidoSaludChanged();
    partial void OnAtendidoSaludCualChanging(string value);
    partial void OnAtendidoSaludCualChanged();
    partial void OnAtendidoSaludFrecuenciaChanging(System.Nullable<int> value);
    partial void OnAtendidoSaludFrecuenciaChanged();
    partial void OnDiagnosticoMedicoChanging(System.Nullable<bool> value);
    partial void OnDiagnosticoMedicoChanged();
    partial void OnDiagnosticoMedicoCualChanging(string value);
    partial void OnDiagnosticoMedicoCualChanged();
    partial void OnTerapiaMedicaChanging(System.Nullable<bool> value);
    partial void OnTerapiaMedicaChanged();
    partial void OnTerapiaMedicaCualChanging(string value);
    partial void OnTerapiaMedicaCualChanged();
    partial void OnTerapiaMedicaFrecuenciaChanging(System.Nullable<int> value);
    partial void OnTerapiaMedicaFrecuenciaChanged();
    partial void OnRecibeTratamientoMedicoChanging(System.Nullable<bool> value);
    partial void OnRecibeTratamientoMedicoChanged();
    partial void OnRecibeTratamientoMedicoCualChanging(string value);
    partial void OnRecibeTratamientoMedicoCualChanged();
    partial void OnConsumeMedicamentoChanging(System.Nullable<bool> value);
    partial void OnConsumeMedicamentoChanged();
    partial void OnConsumeMedicamentoFrecuenciaChanging(System.Nullable<int> value);
    partial void OnConsumeMedicamentoFrecuenciaChanged();
    partial void OnConsumeMedicamentoHorarioChanging(string value);
    partial void OnConsumeMedicamentoHorarioChanged();
    partial void OnNombreMedicamentoChanging(string value);
    partial void OnNombreMedicamentoChanged();
    partial void OnConsumeMedicamentoHorarioClaseChanging(string value);
    partial void OnConsumeMedicamentoHorarioClaseChanged();
    partial void OnElementoApoyoChanging(System.Nullable<bool> value);
    partial void OnElementoApoyoChanged();
    partial void OnElementoApoyoCualChanging(string value);
    partial void OnElementoApoyoCualChanged();
    partial void OnDependenciaPersonaChanging(System.Nullable<bool> value);
    partial void OnDependenciaPersonaChanged();
    partial void OnDependenciaPersonaQuienChanging(string value);
    partial void OnDependenciaPersonaQuienChanged();
    partial void OnDependenciaPersonaNivelEducativoChanging(string value);
    partial void OnDependenciaPersonaNivelEducativoChanged();
    partial void OnPersonaCargoChanging(System.Nullable<bool> value);
    partial void OnPersonaCargoChanged();
    partial void OnPersonaCargoQuienChanging(string value);
    partial void OnPersonaCargoQuienChanged();
    partial void OnPersonaCuidadoraChanging(System.Nullable<bool> value);
    partial void OnPersonaCuidadoraChanged();
    partial void OnPersonaCuidadoraNombreChanging(string value);
    partial void OnPersonaCuidadoraNombreChanged();
    partial void OnPersonaCuidadoraParentescoChanging(string value);
    partial void OnPersonaCuidadoraParentescoChanged();
    partial void OnPersonaCuidadoraNivelEducativoChanging(string value);
    partial void OnPersonaCuidadoraNivelEducativoChanged();
    partial void OnPersonaCuidadoraTelefonoChanging(string value);
    partial void OnPersonaCuidadoraTelefonoChanged();
    partial void OnPersonaCuidadoraEmailChanging(string value);
    partial void OnPersonaCuidadoraEmailChanged();
    partial void OnNombrePersonaCrianzaChanging(string value);
    partial void OnNombrePersonaCrianzaChanged();
    partial void OnRecibeSubsidioChanging(System.Nullable<bool> value);
    partial void OnRecibeSubsidioChanged();
    partial void OnRecibeSubsidioCualChanging(string value);
    partial void OnRecibeSubsidioCualChanged();
    partial void OnMatriculadoInstitucionAnteriorChanging(System.Nullable<bool> value);
    partial void OnMatriculadoInstitucionAnteriorChanged();
    partial void OnMatriculadoInstitucionAnteriorCualChanging(string value);
    partial void OnMatriculadoInstitucionAnteriorCualChanged();
    partial void OnMatriculadoInstitucionAnteriorPorqueChanging(string value);
    partial void OnMatriculadoInstitucionAnteriorPorqueChanged();
    partial void OnCuantoSinEstudiarChanging(System.Nullable<int> value);
    partial void OnCuantoSinEstudiarChanged();
    partial void OnQueAprendioChanging(string value);
    partial void OnQueAprendioChanged();
    partial void OnUltimoGradoChanging(string value);
    partial void OnUltimoGradoChanged();
    partial void OnAproboChanging(System.Nullable<bool> value);
    partial void OnAproboChanged();
    partial void OnObservacionCambioChanging(string value);
    partial void OnObservacionCambioChanged();
    partial void OnRazonNoEstudioChanging(string value);
    partial void OnRazonNoEstudioChanged();
    partial void OnProgramaComplementarioChanging(System.Nullable<bool> value);
    partial void OnProgramaComplementarioChanged();
    partial void OnProgramaComplementarioCualChanging(string value);
    partial void OnProgramaComplementarioCualChanged();
    partial void OnIdInstitucionChanging(int value);
    partial void OnIdInstitucionChanged();
    partial void OnIdSedeChanging(int value);
    partial void OnIdSedeChanged();
    partial void OnJornadaChanging(string value);
    partial void OnJornadaChanged();
    partial void OnMedioTransporteChanging(string value);
    partial void OnMedioTransporteChanged();
    partial void OnGradoChanging(string value);
    partial void OnGradoChanged();
    partial void OnDepartamentoDiligenciaChanging(string value);
    partial void OnDepartamentoDiligenciaChanged();
    partial void OnMunicipioDiligenciaChanging(string value);
    partial void OnMunicipioDiligenciaChanged();
    partial void OnNombreApellidoDiligenciaChanging(string value);
    partial void OnNombreApellidoDiligenciaChanged();
    partial void OnRolDiligenciaChanging(string value);
    partial void OnRolDiligenciaChanged();
    partial void OnFechaDiligenciaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaDiligenciaChanged();
    partial void OnFechaModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificacionChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public Estudiante()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocumentoIdentidad", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TipoDocumentoIdentidad
		{
			get
			{
				return this._TipoDocumentoIdentidad;
			}
			set
			{
				if ((this._TipoDocumentoIdentidad != value))
				{
					this.OnTipoDocumentoIdentidadChanging(value);
					this.SendPropertyChanging();
					this._TipoDocumentoIdentidad = value;
					this.SendPropertyChanged("TipoDocumentoIdentidad");
					this.OnTipoDocumentoIdentidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentoIdentidad", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string DocumentoIdentidad
		{
			get
			{
				return this._DocumentoIdentidad;
			}
			set
			{
				if ((this._DocumentoIdentidad != value))
				{
					this.OnDocumentoIdentidadChanging(value);
					this.SendPropertyChanging();
					this._DocumentoIdentidad = value;
					this.SendPropertyChanged("DocumentoIdentidad");
					this.OnDocumentoIdentidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PrimerApellido
		{
			get
			{
				return this._PrimerApellido;
			}
			set
			{
				if ((this._PrimerApellido != value))
				{
					this.OnPrimerApellidoChanging(value);
					this.SendPropertyChanging();
					this._PrimerApellido = value;
					this.SendPropertyChanged("PrimerApellido");
					this.OnPrimerApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegundoApellido
		{
			get
			{
				return this._SegundoApellido;
			}
			set
			{
				if ((this._SegundoApellido != value))
				{
					this.OnSegundoApellidoChanging(value);
					this.SendPropertyChanging();
					this._SegundoApellido = value;
					this.SendPropertyChanged("SegundoApellido");
					this.OnSegundoApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PrimerNombre
		{
			get
			{
				return this._PrimerNombre;
			}
			set
			{
				if ((this._PrimerNombre != value))
				{
					this.OnPrimerNombreChanging(value);
					this.SendPropertyChanging();
					this._PrimerNombre = value;
					this.SendPropertyChanged("PrimerNombre");
					this.OnPrimerNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this.OnSegundoNombreChanging(value);
					this.SendPropertyChanging();
					this._SegundoNombre = value;
					this.SendPropertyChanged("SegundoNombre");
					this.OnSegundoNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this.OnGeneroChanging(value);
					this.SendPropertyChanging();
					this._Genero = value;
					this.SendPropertyChanged("Genero");
					this.OnGeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartamentoNacimiento", DbType="VarChar(2)")]
		public string DepartamentoNacimiento
		{
			get
			{
				return this._DepartamentoNacimiento;
			}
			set
			{
				if ((this._DepartamentoNacimiento != value))
				{
					this.OnDepartamentoNacimientoChanging(value);
					this.SendPropertyChanging();
					this._DepartamentoNacimiento = value;
					this.SendPropertyChanged("DepartamentoNacimiento");
					this.OnDepartamentoNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioNacimiento", DbType="VarChar(3)")]
		public string MunicipioNacimiento
		{
			get
			{
				return this._MunicipioNacimiento;
			}
			set
			{
				if ((this._MunicipioNacimiento != value))
				{
					this.OnMunicipioNacimientoChanging(value);
					this.SendPropertyChanging();
					this._MunicipioNacimiento = value;
					this.SendPropertyChanged("MunicipioNacimiento");
					this.OnMunicipioNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartamentoDomicilio", DbType="VarChar(2)")]
		public string DepartamentoDomicilio
		{
			get
			{
				return this._DepartamentoDomicilio;
			}
			set
			{
				if ((this._DepartamentoDomicilio != value))
				{
					this.OnDepartamentoDomicilioChanging(value);
					this.SendPropertyChanging();
					this._DepartamentoDomicilio = value;
					this.SendPropertyChanged("DepartamentoDomicilio");
					this.OnDepartamentoDomicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioDomicilio", DbType="VarChar(3)")]
		public string MunicipioDomicilio
		{
			get
			{
				return this._MunicipioDomicilio;
			}
			set
			{
				if ((this._MunicipioDomicilio != value))
				{
					this.OnMunicipioDomicilioChanging(value);
					this.SendPropertyChanging();
					this._MunicipioDomicilio = value;
					this.SendPropertyChanged("MunicipioDomicilio");
					this.OnMunicipioDomicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(20)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarrioVereda", DbType="VarChar(30)")]
		public string BarrioVereda
		{
			get
			{
				return this._BarrioVereda;
			}
			set
			{
				if ((this._BarrioVereda != value))
				{
					this.OnBarrioVeredaChanging(value);
					this.SendPropertyChanging();
					this._BarrioVereda = value;
					this.SendPropertyChanged("BarrioVereda");
					this.OnBarrioVeredaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(10)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="VarChar(50)")]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this.OnCorreoElectronicoChanging(value);
					this.SendPropertyChanging();
					this._CorreoElectronico = value;
					this.SendPropertyChanged("CorreoElectronico");
					this.OnCorreoElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModalidadProteccion", DbType="Bit")]
		public System.Nullable<bool> ModalidadProteccion
		{
			get
			{
				return this._ModalidadProteccion;
			}
			set
			{
				if ((this._ModalidadProteccion != value))
				{
					this.OnModalidadProteccionChanging(value);
					this.SendPropertyChanging();
					this._ModalidadProteccion = value;
					this.SendPropertyChanged("ModalidadProteccion");
					this.OnModalidadProteccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModalidadProtecciónCual", DbType="VarChar(30)")]
		public string ModalidadProtecciónCual
		{
			get
			{
				return this._ModalidadProtecciónCual;
			}
			set
			{
				if ((this._ModalidadProtecciónCual != value))
				{
					this.OnModalidadProtecciónCualChanging(value);
					this.SendPropertyChanging();
					this._ModalidadProtecciónCual = value;
					this.SendPropertyChanged("ModalidadProtecciónCual");
					this.OnModalidadProtecciónCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupacion", DbType="VarChar(30)")]
		public string Ocupacion
		{
			get
			{
				return this._Ocupacion;
			}
			set
			{
				if ((this._Ocupacion != value))
				{
					this.OnOcupacionChanging(value);
					this.SendPropertyChanging();
					this._Ocupacion = value;
					this.SendPropertyChanged("Ocupacion");
					this.OnOcupacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupoEtnico", DbType="Bit")]
		public System.Nullable<bool> GrupoEtnico
		{
			get
			{
				return this._GrupoEtnico;
			}
			set
			{
				if ((this._GrupoEtnico != value))
				{
					this.OnGrupoEtnicoChanging(value);
					this.SendPropertyChanging();
					this._GrupoEtnico = value;
					this.SendPropertyChanged("GrupoEtnico");
					this.OnGrupoEtnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupoEtnicoCual", DbType="VarChar(30)")]
		public string GrupoEtnicoCual
		{
			get
			{
				return this._GrupoEtnicoCual;
			}
			set
			{
				if ((this._GrupoEtnicoCual != value))
				{
					this.OnGrupoEtnicoCualChanging(value);
					this.SendPropertyChanging();
					this._GrupoEtnicoCual = value;
					this.SendPropertyChanged("GrupoEtnicoCual");
					this.OnGrupoEtnicoCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VictimaConflictoArmado", DbType="Bit")]
		public System.Nullable<bool> VictimaConflictoArmado
		{
			get
			{
				return this._VictimaConflictoArmado;
			}
			set
			{
				if ((this._VictimaConflictoArmado != value))
				{
					this.OnVictimaConflictoArmadoChanging(value);
					this.SendPropertyChanging();
					this._VictimaConflictoArmado = value;
					this.SendPropertyChanged("VictimaConflictoArmado");
					this.OnVictimaConflictoArmadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VictimaConflictoArmadoCertificado", DbType="Bit")]
		public System.Nullable<bool> VictimaConflictoArmadoCertificado
		{
			get
			{
				return this._VictimaConflictoArmadoCertificado;
			}
			set
			{
				if ((this._VictimaConflictoArmadoCertificado != value))
				{
					this.OnVictimaConflictoArmadoCertificadoChanging(value);
					this.SendPropertyChanging();
					this._VictimaConflictoArmadoCertificado = value;
					this.SendPropertyChanged("VictimaConflictoArmadoCertificado");
					this.OnVictimaConflictoArmadoCertificadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discapacidad", DbType="Bit")]
		public System.Nullable<bool> Discapacidad
		{
			get
			{
				return this._Discapacidad;
			}
			set
			{
				if ((this._Discapacidad != value))
				{
					this.OnDiscapacidadChanging(value);
					this.SendPropertyChanging();
					this._Discapacidad = value;
					this.SendPropertyChanged("Discapacidad");
					this.OnDiscapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscapacidadCertificado", DbType="Bit")]
		public System.Nullable<bool> DiscapacidadCertificado
		{
			get
			{
				return this._DiscapacidadCertificado;
			}
			set
			{
				if ((this._DiscapacidadCertificado != value))
				{
					this.OnDiscapacidadCertificadoChanging(value);
					this.SendPropertyChanging();
					this._DiscapacidadCertificado = value;
					this.SendPropertyChanged("DiscapacidadCertificado");
					this.OnDiscapacidadCertificadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistroCaracterizacionDiscapacidad", DbType="Bit")]
		public System.Nullable<bool> RegistroCaracterizacionDiscapacidad
		{
			get
			{
				return this._RegistroCaracterizacionDiscapacidad;
			}
			set
			{
				if ((this._RegistroCaracterizacionDiscapacidad != value))
				{
					this.OnRegistroCaracterizacionDiscapacidadChanging(value);
					this.SendPropertyChanging();
					this._RegistroCaracterizacionDiscapacidad = value;
					this.SendPropertyChanged("RegistroCaracterizacionDiscapacidad");
					this.OnRegistroCaracterizacionDiscapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfiliacionSistemaSalud", DbType="VarChar(15)")]
		public string AfiliacionSistemaSalud
		{
			get
			{
				return this._AfiliacionSistemaSalud;
			}
			set
			{
				if ((this._AfiliacionSistemaSalud != value))
				{
					this.OnAfiliacionSistemaSaludChanging(value);
					this.SendPropertyChanging();
					this._AfiliacionSistemaSalud = value;
					this.SendPropertyChanged("AfiliacionSistemaSalud");
					this.OnAfiliacionSistemaSaludChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPS", DbType="VarChar(50)")]
		public string EPS
		{
			get
			{
				return this._EPS;
			}
			set
			{
				if ((this._EPS != value))
				{
					this.OnEPSChanging(value);
					this.SendPropertyChanging();
					this._EPS = value;
					this.SendPropertyChanged("EPS");
					this.OnEPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AtendidoSalud", DbType="Bit")]
		public System.Nullable<bool> AtendidoSalud
		{
			get
			{
				return this._AtendidoSalud;
			}
			set
			{
				if ((this._AtendidoSalud != value))
				{
					this.OnAtendidoSaludChanging(value);
					this.SendPropertyChanging();
					this._AtendidoSalud = value;
					this.SendPropertyChanged("AtendidoSalud");
					this.OnAtendidoSaludChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AtendidoSaludCual", DbType="VarChar(20)")]
		public string AtendidoSaludCual
		{
			get
			{
				return this._AtendidoSaludCual;
			}
			set
			{
				if ((this._AtendidoSaludCual != value))
				{
					this.OnAtendidoSaludCualChanging(value);
					this.SendPropertyChanging();
					this._AtendidoSaludCual = value;
					this.SendPropertyChanged("AtendidoSaludCual");
					this.OnAtendidoSaludCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AtendidoSaludFrecuencia", DbType="Int")]
		public System.Nullable<int> AtendidoSaludFrecuencia
		{
			get
			{
				return this._AtendidoSaludFrecuencia;
			}
			set
			{
				if ((this._AtendidoSaludFrecuencia != value))
				{
					this.OnAtendidoSaludFrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._AtendidoSaludFrecuencia = value;
					this.SendPropertyChanged("AtendidoSaludFrecuencia");
					this.OnAtendidoSaludFrecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiagnosticoMedico", DbType="Bit")]
		public System.Nullable<bool> DiagnosticoMedico
		{
			get
			{
				return this._DiagnosticoMedico;
			}
			set
			{
				if ((this._DiagnosticoMedico != value))
				{
					this.OnDiagnosticoMedicoChanging(value);
					this.SendPropertyChanging();
					this._DiagnosticoMedico = value;
					this.SendPropertyChanged("DiagnosticoMedico");
					this.OnDiagnosticoMedicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiagnosticoMedicoCual", DbType="VarChar(20)")]
		public string DiagnosticoMedicoCual
		{
			get
			{
				return this._DiagnosticoMedicoCual;
			}
			set
			{
				if ((this._DiagnosticoMedicoCual != value))
				{
					this.OnDiagnosticoMedicoCualChanging(value);
					this.SendPropertyChanging();
					this._DiagnosticoMedicoCual = value;
					this.SendPropertyChanged("DiagnosticoMedicoCual");
					this.OnDiagnosticoMedicoCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerapiaMedica", DbType="Bit")]
		public System.Nullable<bool> TerapiaMedica
		{
			get
			{
				return this._TerapiaMedica;
			}
			set
			{
				if ((this._TerapiaMedica != value))
				{
					this.OnTerapiaMedicaChanging(value);
					this.SendPropertyChanging();
					this._TerapiaMedica = value;
					this.SendPropertyChanged("TerapiaMedica");
					this.OnTerapiaMedicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerapiaMedicaCual", DbType="VarChar(20)")]
		public string TerapiaMedicaCual
		{
			get
			{
				return this._TerapiaMedicaCual;
			}
			set
			{
				if ((this._TerapiaMedicaCual != value))
				{
					this.OnTerapiaMedicaCualChanging(value);
					this.SendPropertyChanging();
					this._TerapiaMedicaCual = value;
					this.SendPropertyChanged("TerapiaMedicaCual");
					this.OnTerapiaMedicaCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerapiaMedicaFrecuencia", DbType="Int")]
		public System.Nullable<int> TerapiaMedicaFrecuencia
		{
			get
			{
				return this._TerapiaMedicaFrecuencia;
			}
			set
			{
				if ((this._TerapiaMedicaFrecuencia != value))
				{
					this.OnTerapiaMedicaFrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._TerapiaMedicaFrecuencia = value;
					this.SendPropertyChanged("TerapiaMedicaFrecuencia");
					this.OnTerapiaMedicaFrecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecibeTratamientoMedico", DbType="Bit")]
		public System.Nullable<bool> RecibeTratamientoMedico
		{
			get
			{
				return this._RecibeTratamientoMedico;
			}
			set
			{
				if ((this._RecibeTratamientoMedico != value))
				{
					this.OnRecibeTratamientoMedicoChanging(value);
					this.SendPropertyChanging();
					this._RecibeTratamientoMedico = value;
					this.SendPropertyChanged("RecibeTratamientoMedico");
					this.OnRecibeTratamientoMedicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecibeTratamientoMedicoCual", DbType="VarChar(20)")]
		public string RecibeTratamientoMedicoCual
		{
			get
			{
				return this._RecibeTratamientoMedicoCual;
			}
			set
			{
				if ((this._RecibeTratamientoMedicoCual != value))
				{
					this.OnRecibeTratamientoMedicoCualChanging(value);
					this.SendPropertyChanging();
					this._RecibeTratamientoMedicoCual = value;
					this.SendPropertyChanged("RecibeTratamientoMedicoCual");
					this.OnRecibeTratamientoMedicoCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumeMedicamento", DbType="Bit")]
		public System.Nullable<bool> ConsumeMedicamento
		{
			get
			{
				return this._ConsumeMedicamento;
			}
			set
			{
				if ((this._ConsumeMedicamento != value))
				{
					this.OnConsumeMedicamentoChanging(value);
					this.SendPropertyChanging();
					this._ConsumeMedicamento = value;
					this.SendPropertyChanged("ConsumeMedicamento");
					this.OnConsumeMedicamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumeMedicamentoFrecuencia", DbType="Int")]
		public System.Nullable<int> ConsumeMedicamentoFrecuencia
		{
			get
			{
				return this._ConsumeMedicamentoFrecuencia;
			}
			set
			{
				if ((this._ConsumeMedicamentoFrecuencia != value))
				{
					this.OnConsumeMedicamentoFrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._ConsumeMedicamentoFrecuencia = value;
					this.SendPropertyChanged("ConsumeMedicamentoFrecuencia");
					this.OnConsumeMedicamentoFrecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumeMedicamentoHorario", DbType="VarChar(50)")]
		public string ConsumeMedicamentoHorario
		{
			get
			{
				return this._ConsumeMedicamentoHorario;
			}
			set
			{
				if ((this._ConsumeMedicamentoHorario != value))
				{
					this.OnConsumeMedicamentoHorarioChanging(value);
					this.SendPropertyChanging();
					this._ConsumeMedicamentoHorario = value;
					this.SendPropertyChanged("ConsumeMedicamentoHorario");
					this.OnConsumeMedicamentoHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMedicamento", DbType="VarChar(20)")]
		public string NombreMedicamento
		{
			get
			{
				return this._NombreMedicamento;
			}
			set
			{
				if ((this._NombreMedicamento != value))
				{
					this.OnNombreMedicamentoChanging(value);
					this.SendPropertyChanging();
					this._NombreMedicamento = value;
					this.SendPropertyChanged("NombreMedicamento");
					this.OnNombreMedicamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumeMedicamentoHorarioClase", DbType="VarChar(20)")]
		public string ConsumeMedicamentoHorarioClase
		{
			get
			{
				return this._ConsumeMedicamentoHorarioClase;
			}
			set
			{
				if ((this._ConsumeMedicamentoHorarioClase != value))
				{
					this.OnConsumeMedicamentoHorarioClaseChanging(value);
					this.SendPropertyChanging();
					this._ConsumeMedicamentoHorarioClase = value;
					this.SendPropertyChanged("ConsumeMedicamentoHorarioClase");
					this.OnConsumeMedicamentoHorarioClaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElementoApoyo", DbType="Bit")]
		public System.Nullable<bool> ElementoApoyo
		{
			get
			{
				return this._ElementoApoyo;
			}
			set
			{
				if ((this._ElementoApoyo != value))
				{
					this.OnElementoApoyoChanging(value);
					this.SendPropertyChanging();
					this._ElementoApoyo = value;
					this.SendPropertyChanged("ElementoApoyo");
					this.OnElementoApoyoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElementoApoyoCual", DbType="VarChar(20)")]
		public string ElementoApoyoCual
		{
			get
			{
				return this._ElementoApoyoCual;
			}
			set
			{
				if ((this._ElementoApoyoCual != value))
				{
					this.OnElementoApoyoCualChanging(value);
					this.SendPropertyChanging();
					this._ElementoApoyoCual = value;
					this.SendPropertyChanged("ElementoApoyoCual");
					this.OnElementoApoyoCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DependenciaPersona", DbType="Bit")]
		public System.Nullable<bool> DependenciaPersona
		{
			get
			{
				return this._DependenciaPersona;
			}
			set
			{
				if ((this._DependenciaPersona != value))
				{
					this.OnDependenciaPersonaChanging(value);
					this.SendPropertyChanging();
					this._DependenciaPersona = value;
					this.SendPropertyChanged("DependenciaPersona");
					this.OnDependenciaPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DependenciaPersonaQuien", DbType="VarChar(20)")]
		public string DependenciaPersonaQuien
		{
			get
			{
				return this._DependenciaPersonaQuien;
			}
			set
			{
				if ((this._DependenciaPersonaQuien != value))
				{
					this.OnDependenciaPersonaQuienChanging(value);
					this.SendPropertyChanging();
					this._DependenciaPersonaQuien = value;
					this.SendPropertyChanged("DependenciaPersonaQuien");
					this.OnDependenciaPersonaQuienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DependenciaPersonaNivelEducativo", DbType="VarChar(20)")]
		public string DependenciaPersonaNivelEducativo
		{
			get
			{
				return this._DependenciaPersonaNivelEducativo;
			}
			set
			{
				if ((this._DependenciaPersonaNivelEducativo != value))
				{
					this.OnDependenciaPersonaNivelEducativoChanging(value);
					this.SendPropertyChanging();
					this._DependenciaPersonaNivelEducativo = value;
					this.SendPropertyChanged("DependenciaPersonaNivelEducativo");
					this.OnDependenciaPersonaNivelEducativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaCargo", DbType="Bit")]
		public System.Nullable<bool> PersonaCargo
		{
			get
			{
				return this._PersonaCargo;
			}
			set
			{
				if ((this._PersonaCargo != value))
				{
					this.OnPersonaCargoChanging(value);
					this.SendPropertyChanging();
					this._PersonaCargo = value;
					this.SendPropertyChanged("PersonaCargo");
					this.OnPersonaCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaCargoQuien", DbType="VarChar(20)")]
		public string PersonaCargoQuien
		{
			get
			{
				return this._PersonaCargoQuien;
			}
			set
			{
				if ((this._PersonaCargoQuien != value))
				{
					this.OnPersonaCargoQuienChanging(value);
					this.SendPropertyChanging();
					this._PersonaCargoQuien = value;
					this.SendPropertyChanged("PersonaCargoQuien");
					this.OnPersonaCargoQuienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaCuidadora", DbType="Bit")]
		public System.Nullable<bool> PersonaCuidadora
		{
			get
			{
				return this._PersonaCuidadora;
			}
			set
			{
				if ((this._PersonaCuidadora != value))
				{
					this.OnPersonaCuidadoraChanging(value);
					this.SendPropertyChanging();
					this._PersonaCuidadora = value;
					this.SendPropertyChanged("PersonaCuidadora");
					this.OnPersonaCuidadoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaCuidadoraNombre", DbType="VarChar(20)")]
		public string PersonaCuidadoraNombre
		{
			get
			{
				return this._PersonaCuidadoraNombre;
			}
			set
			{
				if ((this._PersonaCuidadoraNombre != value))
				{
					this.OnPersonaCuidadoraNombreChanging(value);
					this.SendPropertyChanging();
					this._PersonaCuidadoraNombre = value;
					this.SendPropertyChanged("PersonaCuidadoraNombre");
					this.OnPersonaCuidadoraNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaCuidadoraParentesco", DbType="VarChar(20)")]
		public string PersonaCuidadoraParentesco
		{
			get
			{
				return this._PersonaCuidadoraParentesco;
			}
			set
			{
				if ((this._PersonaCuidadoraParentesco != value))
				{
					this.OnPersonaCuidadoraParentescoChanging(value);
					this.SendPropertyChanging();
					this._PersonaCuidadoraParentesco = value;
					this.SendPropertyChanged("PersonaCuidadoraParentesco");
					this.OnPersonaCuidadoraParentescoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaCuidadoraNivelEducativo", DbType="VarChar(20)")]
		public string PersonaCuidadoraNivelEducativo
		{
			get
			{
				return this._PersonaCuidadoraNivelEducativo;
			}
			set
			{
				if ((this._PersonaCuidadoraNivelEducativo != value))
				{
					this.OnPersonaCuidadoraNivelEducativoChanging(value);
					this.SendPropertyChanging();
					this._PersonaCuidadoraNivelEducativo = value;
					this.SendPropertyChanged("PersonaCuidadoraNivelEducativo");
					this.OnPersonaCuidadoraNivelEducativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaCuidadoraTelefono", DbType="VarChar(15)")]
		public string PersonaCuidadoraTelefono
		{
			get
			{
				return this._PersonaCuidadoraTelefono;
			}
			set
			{
				if ((this._PersonaCuidadoraTelefono != value))
				{
					this.OnPersonaCuidadoraTelefonoChanging(value);
					this.SendPropertyChanging();
					this._PersonaCuidadoraTelefono = value;
					this.SendPropertyChanged("PersonaCuidadoraTelefono");
					this.OnPersonaCuidadoraTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaCuidadoraEmail", DbType="VarChar(50)")]
		public string PersonaCuidadoraEmail
		{
			get
			{
				return this._PersonaCuidadoraEmail;
			}
			set
			{
				if ((this._PersonaCuidadoraEmail != value))
				{
					this.OnPersonaCuidadoraEmailChanging(value);
					this.SendPropertyChanging();
					this._PersonaCuidadoraEmail = value;
					this.SendPropertyChanged("PersonaCuidadoraEmail");
					this.OnPersonaCuidadoraEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePersonaCrianza", DbType="VarChar(20)")]
		public string NombrePersonaCrianza
		{
			get
			{
				return this._NombrePersonaCrianza;
			}
			set
			{
				if ((this._NombrePersonaCrianza != value))
				{
					this.OnNombrePersonaCrianzaChanging(value);
					this.SendPropertyChanging();
					this._NombrePersonaCrianza = value;
					this.SendPropertyChanged("NombrePersonaCrianza");
					this.OnNombrePersonaCrianzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecibeSubsidio", DbType="Bit")]
		public System.Nullable<bool> RecibeSubsidio
		{
			get
			{
				return this._RecibeSubsidio;
			}
			set
			{
				if ((this._RecibeSubsidio != value))
				{
					this.OnRecibeSubsidioChanging(value);
					this.SendPropertyChanging();
					this._RecibeSubsidio = value;
					this.SendPropertyChanged("RecibeSubsidio");
					this.OnRecibeSubsidioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecibeSubsidioCual", DbType="VarChar(20)")]
		public string RecibeSubsidioCual
		{
			get
			{
				return this._RecibeSubsidioCual;
			}
			set
			{
				if ((this._RecibeSubsidioCual != value))
				{
					this.OnRecibeSubsidioCualChanging(value);
					this.SendPropertyChanging();
					this._RecibeSubsidioCual = value;
					this.SendPropertyChanged("RecibeSubsidioCual");
					this.OnRecibeSubsidioCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatriculadoInstitucionAnterior", DbType="Bit")]
		public System.Nullable<bool> MatriculadoInstitucionAnterior
		{
			get
			{
				return this._MatriculadoInstitucionAnterior;
			}
			set
			{
				if ((this._MatriculadoInstitucionAnterior != value))
				{
					this.OnMatriculadoInstitucionAnteriorChanging(value);
					this.SendPropertyChanging();
					this._MatriculadoInstitucionAnterior = value;
					this.SendPropertyChanged("MatriculadoInstitucionAnterior");
					this.OnMatriculadoInstitucionAnteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatriculadoInstitucionAnteriorCual", DbType="VarChar(20)")]
		public string MatriculadoInstitucionAnteriorCual
		{
			get
			{
				return this._MatriculadoInstitucionAnteriorCual;
			}
			set
			{
				if ((this._MatriculadoInstitucionAnteriorCual != value))
				{
					this.OnMatriculadoInstitucionAnteriorCualChanging(value);
					this.SendPropertyChanging();
					this._MatriculadoInstitucionAnteriorCual = value;
					this.SendPropertyChanged("MatriculadoInstitucionAnteriorCual");
					this.OnMatriculadoInstitucionAnteriorCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatriculadoInstitucionAnteriorPorque", DbType="VarChar(20)")]
		public string MatriculadoInstitucionAnteriorPorque
		{
			get
			{
				return this._MatriculadoInstitucionAnteriorPorque;
			}
			set
			{
				if ((this._MatriculadoInstitucionAnteriorPorque != value))
				{
					this.OnMatriculadoInstitucionAnteriorPorqueChanging(value);
					this.SendPropertyChanging();
					this._MatriculadoInstitucionAnteriorPorque = value;
					this.SendPropertyChanged("MatriculadoInstitucionAnteriorPorque");
					this.OnMatriculadoInstitucionAnteriorPorqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuantoSinEstudiar", DbType="Int")]
		public System.Nullable<int> CuantoSinEstudiar
		{
			get
			{
				return this._CuantoSinEstudiar;
			}
			set
			{
				if ((this._CuantoSinEstudiar != value))
				{
					this.OnCuantoSinEstudiarChanging(value);
					this.SendPropertyChanging();
					this._CuantoSinEstudiar = value;
					this.SendPropertyChanged("CuantoSinEstudiar");
					this.OnCuantoSinEstudiarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueAprendio", DbType="VarChar(50)")]
		public string QueAprendio
		{
			get
			{
				return this._QueAprendio;
			}
			set
			{
				if ((this._QueAprendio != value))
				{
					this.OnQueAprendioChanging(value);
					this.SendPropertyChanging();
					this._QueAprendio = value;
					this.SendPropertyChanged("QueAprendio");
					this.OnQueAprendioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoGrado", DbType="VarChar(20)")]
		public string UltimoGrado
		{
			get
			{
				return this._UltimoGrado;
			}
			set
			{
				if ((this._UltimoGrado != value))
				{
					this.OnUltimoGradoChanging(value);
					this.SendPropertyChanging();
					this._UltimoGrado = value;
					this.SendPropertyChanged("UltimoGrado");
					this.OnUltimoGradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprobo", DbType="Bit")]
		public System.Nullable<bool> Aprobo
		{
			get
			{
				return this._Aprobo;
			}
			set
			{
				if ((this._Aprobo != value))
				{
					this.OnAproboChanging(value);
					this.SendPropertyChanging();
					this._Aprobo = value;
					this.SendPropertyChanged("Aprobo");
					this.OnAproboChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObservacionCambio", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ObservacionCambio
		{
			get
			{
				return this._ObservacionCambio;
			}
			set
			{
				if ((this._ObservacionCambio != value))
				{
					this.OnObservacionCambioChanging(value);
					this.SendPropertyChanging();
					this._ObservacionCambio = value;
					this.SendPropertyChanged("ObservacionCambio");
					this.OnObservacionCambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonNoEstudio", DbType="VarChar(20)")]
		public string RazonNoEstudio
		{
			get
			{
				return this._RazonNoEstudio;
			}
			set
			{
				if ((this._RazonNoEstudio != value))
				{
					this.OnRazonNoEstudioChanging(value);
					this.SendPropertyChanging();
					this._RazonNoEstudio = value;
					this.SendPropertyChanged("RazonNoEstudio");
					this.OnRazonNoEstudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramaComplementario", DbType="Bit")]
		public System.Nullable<bool> ProgramaComplementario
		{
			get
			{
				return this._ProgramaComplementario;
			}
			set
			{
				if ((this._ProgramaComplementario != value))
				{
					this.OnProgramaComplementarioChanging(value);
					this.SendPropertyChanging();
					this._ProgramaComplementario = value;
					this.SendPropertyChanged("ProgramaComplementario");
					this.OnProgramaComplementarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramaComplementarioCual", DbType="VarChar(20)")]
		public string ProgramaComplementarioCual
		{
			get
			{
				return this._ProgramaComplementarioCual;
			}
			set
			{
				if ((this._ProgramaComplementarioCual != value))
				{
					this.OnProgramaComplementarioCualChanging(value);
					this.SendPropertyChanging();
					this._ProgramaComplementarioCual = value;
					this.SendPropertyChanged("ProgramaComplementarioCual");
					this.OnProgramaComplementarioCualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInstitucion", DbType="Int NOT NULL")]
		public int IdInstitucion
		{
			get
			{
				return this._IdInstitucion;
			}
			set
			{
				if ((this._IdInstitucion != value))
				{
					this.OnIdInstitucionChanging(value);
					this.SendPropertyChanging();
					this._IdInstitucion = value;
					this.SendPropertyChanged("IdInstitucion");
					this.OnIdInstitucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSede", DbType="Int NOT NULL")]
		public int IdSede
		{
			get
			{
				return this._IdSede;
			}
			set
			{
				if ((this._IdSede != value))
				{
					this.OnIdSedeChanging(value);
					this.SendPropertyChanging();
					this._IdSede = value;
					this.SendPropertyChanged("IdSede");
					this.OnIdSedeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jornada", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Jornada
		{
			get
			{
				return this._Jornada;
			}
			set
			{
				if ((this._Jornada != value))
				{
					this.OnJornadaChanging(value);
					this.SendPropertyChanging();
					this._Jornada = value;
					this.SendPropertyChanged("Jornada");
					this.OnJornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedioTransporte", DbType="VarChar(20)")]
		public string MedioTransporte
		{
			get
			{
				return this._MedioTransporte;
			}
			set
			{
				if ((this._MedioTransporte != value))
				{
					this.OnMedioTransporteChanging(value);
					this.SendPropertyChanging();
					this._MedioTransporte = value;
					this.SendPropertyChanged("MedioTransporte");
					this.OnMedioTransporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Grado
		{
			get
			{
				return this._Grado;
			}
			set
			{
				if ((this._Grado != value))
				{
					this.OnGradoChanging(value);
					this.SendPropertyChanging();
					this._Grado = value;
					this.SendPropertyChanged("Grado");
					this.OnGradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartamentoDiligencia", DbType="VarChar(2)")]
		public string DepartamentoDiligencia
		{
			get
			{
				return this._DepartamentoDiligencia;
			}
			set
			{
				if ((this._DepartamentoDiligencia != value))
				{
					this.OnDepartamentoDiligenciaChanging(value);
					this.SendPropertyChanging();
					this._DepartamentoDiligencia = value;
					this.SendPropertyChanged("DepartamentoDiligencia");
					this.OnDepartamentoDiligenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioDiligencia", DbType="VarChar(3)")]
		public string MunicipioDiligencia
		{
			get
			{
				return this._MunicipioDiligencia;
			}
			set
			{
				if ((this._MunicipioDiligencia != value))
				{
					this.OnMunicipioDiligenciaChanging(value);
					this.SendPropertyChanging();
					this._MunicipioDiligencia = value;
					this.SendPropertyChanged("MunicipioDiligencia");
					this.OnMunicipioDiligenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreApellidoDiligencia", DbType="VarChar(50)")]
		public string NombreApellidoDiligencia
		{
			get
			{
				return this._NombreApellidoDiligencia;
			}
			set
			{
				if ((this._NombreApellidoDiligencia != value))
				{
					this.OnNombreApellidoDiligenciaChanging(value);
					this.SendPropertyChanging();
					this._NombreApellidoDiligencia = value;
					this.SendPropertyChanged("NombreApellidoDiligencia");
					this.OnNombreApellidoDiligenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolDiligencia", DbType="VarChar(30)")]
		public string RolDiligencia
		{
			get
			{
				return this._RolDiligencia;
			}
			set
			{
				if ((this._RolDiligencia != value))
				{
					this.OnRolDiligenciaChanging(value);
					this.SendPropertyChanging();
					this._RolDiligencia = value;
					this.SendPropertyChanged("RolDiligencia");
					this.OnRolDiligenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDiligencia", DbType="Date")]
		public System.Nullable<System.DateTime> FechaDiligencia
		{
			get
			{
				return this._FechaDiligencia;
			}
			set
			{
				if ((this._FechaDiligencia != value))
				{
					this.OnFechaDiligenciaChanging(value);
					this.SendPropertyChanging();
					this._FechaDiligencia = value;
					this.SendPropertyChanged("FechaDiligencia");
					this.OnFechaDiligenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
