#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEducativo.Models.Configuracion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PIAR")]
	public partial class ConfiguracionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertRol(Rol instance);
    partial void UpdateRol(Rol instance);
    partial void DeleteRol(Rol instance);
    partial void InsertTipoVInculacion(TipoVInculacion instance);
    partial void UpdateTipoVInculacion(TipoVInculacion instance);
    partial void DeleteTipoVInculacion(TipoVInculacion instance);
    partial void InsertAspNetUsers(AspNetUsers instance);
    partial void UpdateAspNetUsers(AspNetUsers instance);
    partial void DeleteAspNetUsers(AspNetUsers instance);
    partial void InsertCargo(Cargo instance);
    partial void UpdateCargo(Cargo instance);
    partial void DeleteCargo(Cargo instance);
    partial void InsertGradoEscalafon(GradoEscalafon instance);
    partial void UpdateGradoEscalafon(GradoEscalafon instance);
    partial void DeleteGradoEscalafon(GradoEscalafon instance);
    partial void InsertPerfilUsuario(PerfilUsuario instance);
    partial void UpdatePerfilUsuario(PerfilUsuario instance);
    partial void DeletePerfilUsuario(PerfilUsuario instance);
    partial void InsertAreaDesempeno(AreaDesempeno instance);
    partial void UpdateAreaDesempeno(AreaDesempeno instance);
    partial void DeleteAreaDesempeno(AreaDesempeno instance);
    partial void InsertRecuperacionContrasena(RecuperacionContrasena instance);
    partial void UpdateRecuperacionContrasena(RecuperacionContrasena instance);
    partial void DeleteRecuperacionContrasena(RecuperacionContrasena instance);
    #endregion
		
		public ConfiguracionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PIARConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Rol> Rol
		{
			get
			{
				return this.GetTable<Rol>();
			}
		}
		
		public System.Data.Linq.Table<TipoVInculacion> TipoVInculacion
		{
			get
			{
				return this.GetTable<TipoVInculacion>();
			}
		}
		
		public System.Data.Linq.Table<AspNetUsers> AspNetUsers
		{
			get
			{
				return this.GetTable<AspNetUsers>();
			}
		}
		
		public System.Data.Linq.Table<Cargo> Cargo
		{
			get
			{
				return this.GetTable<Cargo>();
			}
		}
		
		public System.Data.Linq.Table<GradoEscalafon> GradoEscalafon
		{
			get
			{
				return this.GetTable<GradoEscalafon>();
			}
		}
		
		public System.Data.Linq.Table<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this.GetTable<PerfilUsuario>();
			}
		}
		
		public System.Data.Linq.Table<AreaDesempeno> AreaDesempeno
		{
			get
			{
				return this.GetTable<AreaDesempeno>();
			}
		}
		
		public System.Data.Linq.Table<RegistroAreaDesempeno> RegistroAreaDesempeno
		{
			get
			{
				return this.GetTable<RegistroAreaDesempeno>();
			}
		}
		
		public System.Data.Linq.Table<RecuperacionContrasena> RecuperacionContrasena
		{
			get
			{
				return this.GetTable<RecuperacionContrasena>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
	public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NombreRol;
		
		private bool _Eliminado;
		
		private EntitySet<PerfilUsuario> _PerfilUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreRolChanging(string value);
    partial void OnNombreRolChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public Rol()
		{
			this._PerfilUsuario = new EntitySet<PerfilUsuario>(new Action<PerfilUsuario>(this.attach_PerfilUsuario), new Action<PerfilUsuario>(this.detach_PerfilUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreRol", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string NombreRol
		{
			get
			{
				return this._NombreRol;
			}
			set
			{
				if ((this._NombreRol != value))
				{
					this.OnNombreRolChanging(value);
					this.SendPropertyChanging();
					this._NombreRol = value;
					this.SendPropertyChanged("NombreRol");
					this.OnNombreRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_PerfilUsuario", Storage="_PerfilUsuario", ThisKey="Id", OtherKey="idRol")]
		public EntitySet<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this._PerfilUsuario;
			}
			set
			{
				this._PerfilUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Rol = this;
		}
		
		private void detach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoVInculacion")]
	public partial class TipoVInculacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVinculacion;
		
		private string _TipoVinculacion1;
		
		private EntitySet<PerfilUsuario> _PerfilUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVinculacionChanging(int value);
    partial void OnIdVinculacionChanged();
    partial void OnTipoVinculacion1Changing(string value);
    partial void OnTipoVinculacion1Changed();
    #endregion
		
		public TipoVInculacion()
		{
			this._PerfilUsuario = new EntitySet<PerfilUsuario>(new Action<PerfilUsuario>(this.attach_PerfilUsuario), new Action<PerfilUsuario>(this.detach_PerfilUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVinculacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVinculacion
		{
			get
			{
				return this._IdVinculacion;
			}
			set
			{
				if ((this._IdVinculacion != value))
				{
					this.OnIdVinculacionChanging(value);
					this.SendPropertyChanging();
					this._IdVinculacion = value;
					this.SendPropertyChanged("IdVinculacion");
					this.OnIdVinculacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TipoVinculacion", Storage="_TipoVinculacion1", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TipoVinculacion1
		{
			get
			{
				return this._TipoVinculacion1;
			}
			set
			{
				if ((this._TipoVinculacion1 != value))
				{
					this.OnTipoVinculacion1Changing(value);
					this.SendPropertyChanging();
					this._TipoVinculacion1 = value;
					this.SendPropertyChanged("TipoVinculacion1");
					this.OnTipoVinculacion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoVInculacion_PerfilUsuario", Storage="_PerfilUsuario", ThisKey="IdVinculacion", OtherKey="IdTipoVinculacion")]
		public EntitySet<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this._PerfilUsuario;
			}
			set
			{
				this._PerfilUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.TipoVInculacion = this;
		}
		
		private void detach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.TipoVInculacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AspNetUsers")]
	public partial class AspNetUsers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Email;
		
		private bool _EmailConfirmed;
		
		private string _PasswordHash;
		
		private string _SecurityStamp;
		
		private string _PhoneNumber;
		
		private bool _PhoneNumberConfirmed;
		
		private bool _TwoFactorEnabled;
		
		private System.Nullable<System.DateTime> _LockoutEndDateUtc;
		
		private bool _LockoutEnabled;
		
		private int _AccessFailedCount;
		
		private string _UserName;
		
		private EntitySet<PerfilUsuario> _PerfilUsuario;
		
		private EntitySet<RecuperacionContrasena> _RecuperacionContrasena;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEmailConfirmedChanging(bool value);
    partial void OnEmailConfirmedChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnSecurityStampChanging(string value);
    partial void OnSecurityStampChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnPhoneNumberConfirmedChanging(bool value);
    partial void OnPhoneNumberConfirmedChanged();
    partial void OnTwoFactorEnabledChanging(bool value);
    partial void OnTwoFactorEnabledChanged();
    partial void OnLockoutEndDateUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnLockoutEndDateUtcChanged();
    partial void OnLockoutEnabledChanging(bool value);
    partial void OnLockoutEnabledChanged();
    partial void OnAccessFailedCountChanging(int value);
    partial void OnAccessFailedCountChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public AspNetUsers()
		{
			this._PerfilUsuario = new EntitySet<PerfilUsuario>(new Action<PerfilUsuario>(this.attach_PerfilUsuario), new Action<PerfilUsuario>(this.detach_PerfilUsuario));
			this._RecuperacionContrasena = new EntitySet<RecuperacionContrasena>(new Action<RecuperacionContrasena>(this.attach_RecuperacionContrasena), new Action<RecuperacionContrasena>(this.detach_RecuperacionContrasena));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailConfirmed", DbType="Bit NOT NULL")]
		public bool EmailConfirmed
		{
			get
			{
				return this._EmailConfirmed;
			}
			set
			{
				if ((this._EmailConfirmed != value))
				{
					this.OnEmailConfirmedChanging(value);
					this.SendPropertyChanging();
					this._EmailConfirmed = value;
					this.SendPropertyChanged("EmailConfirmed");
					this.OnEmailConfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="NVarChar(MAX)")]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityStamp", DbType="NVarChar(MAX)")]
		public string SecurityStamp
		{
			get
			{
				return this._SecurityStamp;
			}
			set
			{
				if ((this._SecurityStamp != value))
				{
					this.OnSecurityStampChanging(value);
					this.SendPropertyChanging();
					this._SecurityStamp = value;
					this.SendPropertyChanged("SecurityStamp");
					this.OnSecurityStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(MAX)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumberConfirmed", DbType="Bit NOT NULL")]
		public bool PhoneNumberConfirmed
		{
			get
			{
				return this._PhoneNumberConfirmed;
			}
			set
			{
				if ((this._PhoneNumberConfirmed != value))
				{
					this.OnPhoneNumberConfirmedChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumberConfirmed = value;
					this.SendPropertyChanged("PhoneNumberConfirmed");
					this.OnPhoneNumberConfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwoFactorEnabled", DbType="Bit NOT NULL")]
		public bool TwoFactorEnabled
		{
			get
			{
				return this._TwoFactorEnabled;
			}
			set
			{
				if ((this._TwoFactorEnabled != value))
				{
					this.OnTwoFactorEnabledChanging(value);
					this.SendPropertyChanging();
					this._TwoFactorEnabled = value;
					this.SendPropertyChanged("TwoFactorEnabled");
					this.OnTwoFactorEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockoutEndDateUtc", DbType="DateTime")]
		public System.Nullable<System.DateTime> LockoutEndDateUtc
		{
			get
			{
				return this._LockoutEndDateUtc;
			}
			set
			{
				if ((this._LockoutEndDateUtc != value))
				{
					this.OnLockoutEndDateUtcChanging(value);
					this.SendPropertyChanging();
					this._LockoutEndDateUtc = value;
					this.SendPropertyChanged("LockoutEndDateUtc");
					this.OnLockoutEndDateUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockoutEnabled", DbType="Bit NOT NULL")]
		public bool LockoutEnabled
		{
			get
			{
				return this._LockoutEnabled;
			}
			set
			{
				if ((this._LockoutEnabled != value))
				{
					this.OnLockoutEnabledChanging(value);
					this.SendPropertyChanging();
					this._LockoutEnabled = value;
					this.SendPropertyChanged("LockoutEnabled");
					this.OnLockoutEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessFailedCount", DbType="Int NOT NULL")]
		public int AccessFailedCount
		{
			get
			{
				return this._AccessFailedCount;
			}
			set
			{
				if ((this._AccessFailedCount != value))
				{
					this.OnAccessFailedCountChanging(value);
					this.SendPropertyChanging();
					this._AccessFailedCount = value;
					this.SendPropertyChanged("AccessFailedCount");
					this.OnAccessFailedCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AspNetUsers_PerfilUsuario", Storage="_PerfilUsuario", ThisKey="Id", OtherKey="IdUser")]
		public EntitySet<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this._PerfilUsuario;
			}
			set
			{
				this._PerfilUsuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AspNetUsers_RecuperacionContrasena", Storage="_RecuperacionContrasena", ThisKey="Id", OtherKey="idUser")]
		public EntitySet<RecuperacionContrasena> RecuperacionContrasena
		{
			get
			{
				return this._RecuperacionContrasena;
			}
			set
			{
				this._RecuperacionContrasena.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.AspNetUsers = this;
		}
		
		private void detach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.AspNetUsers = null;
		}
		
		private void attach_RecuperacionContrasena(RecuperacionContrasena entity)
		{
			this.SendPropertyChanging();
			entity.AspNetUsers = this;
		}
		
		private void detach_RecuperacionContrasena(RecuperacionContrasena entity)
		{
			this.SendPropertyChanging();
			entity.AspNetUsers = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cargo")]
	public partial class Cargo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private EntitySet<PerfilUsuario> _PerfilUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Cargo()
		{
			this._PerfilUsuario = new EntitySet<PerfilUsuario>(new Action<PerfilUsuario>(this.attach_PerfilUsuario), new Action<PerfilUsuario>(this.detach_PerfilUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cargo_PerfilUsuario", Storage="_PerfilUsuario", ThisKey="Id", OtherKey="CargoBase")]
		public EntitySet<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this._PerfilUsuario;
			}
			set
			{
				this._PerfilUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Cargo = this;
		}
		
		private void detach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Cargo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GradoEscalafon")]
	public partial class GradoEscalafon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private EntitySet<PerfilUsuario> _PerfilUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public GradoEscalafon()
		{
			this._PerfilUsuario = new EntitySet<PerfilUsuario>(new Action<PerfilUsuario>(this.attach_PerfilUsuario), new Action<PerfilUsuario>(this.detach_PerfilUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GradoEscalafon_PerfilUsuario", Storage="_PerfilUsuario", ThisKey="Id", OtherKey="GradoEscalafon")]
		public EntitySet<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this._PerfilUsuario;
			}
			set
			{
				this._PerfilUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.GradoEscalafon1 = this;
		}
		
		private void detach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.GradoEscalafon1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PerfilUsuario")]
	public partial class PerfilUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _IdUser;
		
		private string _TipoDocumento;
		
		private string _Documento;
		
		private string _CodDepartamentoExpedicion;
		
		private string _CodMunicipioExpedicion;
		
		private string _PrimerNombre;
		
		private string _SegundoNombre;
		
		private string _PrimerApellido;
		
		private string _SegundoApellido;
		
		private System.DateTime _FechaNacimiento;
		
		private System.DateTime _FechaVinculacion;
		
		private int _IdTipoVinculacion;
		
		private string _ZonaAtender;
		
		private int _CargoBase;
		
		private string _Nivel;
		
		private int _IdInstitucionEducativa;
		
		private int _IdSede;
		
		private int _GradoEscalafon;
		
		private string _Titulo;
		
		private int _idRol;
		
		private System.DateTime _FechaCreacion;
		
		private System.DateTime _FechaModificacion;
		
		private bool _Eliminado;
		
		private EntityRef<TipoVInculacion> _TipoVInculacion;
		
		private EntityRef<AspNetUsers> _AspNetUsers;
		
		private EntityRef<GradoEscalafon> _GradoEscalafon1;
		
		private EntityRef<Cargo> _Cargo;
		
		private EntityRef<Rol> _Rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnIdUserChanging(string value);
    partial void OnIdUserChanged();
    partial void OnTipoDocumentoChanging(string value);
    partial void OnTipoDocumentoChanged();
    partial void OnDocumentoChanging(string value);
    partial void OnDocumentoChanged();
    partial void OnCodDepartamentoExpedicionChanging(string value);
    partial void OnCodDepartamentoExpedicionChanged();
    partial void OnCodMunicipioExpedicionChanging(string value);
    partial void OnCodMunicipioExpedicionChanged();
    partial void OnPrimerNombreChanging(string value);
    partial void OnPrimerNombreChanged();
    partial void OnSegundoNombreChanging(string value);
    partial void OnSegundoNombreChanged();
    partial void OnPrimerApellidoChanging(string value);
    partial void OnPrimerApellidoChanged();
    partial void OnSegundoApellidoChanging(string value);
    partial void OnSegundoApellidoChanged();
    partial void OnFechaNacimientoChanging(System.DateTime value);
    partial void OnFechaNacimientoChanged();
    partial void OnFechaVinculacionChanging(System.DateTime value);
    partial void OnFechaVinculacionChanged();
    partial void OnIdTipoVinculacionChanging(int value);
    partial void OnIdTipoVinculacionChanged();
    partial void OnZonaAtenderChanging(string value);
    partial void OnZonaAtenderChanged();
    partial void OnCargoBaseChanging(int value);
    partial void OnCargoBaseChanged();
    partial void OnNivelChanging(string value);
    partial void OnNivelChanged();
    partial void OnIdInstitucionEducativaChanging(int value);
    partial void OnIdInstitucionEducativaChanged();
    partial void OnIdSedeChanging(int value);
    partial void OnIdSedeChanged();
    partial void OnGradoEscalafonChanging(int value);
    partial void OnGradoEscalafonChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnidRolChanging(int value);
    partial void OnidRolChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaModificacionChanging(System.DateTime value);
    partial void OnFechaModificacionChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public PerfilUsuario()
		{
			this._TipoVInculacion = default(EntityRef<TipoVInculacion>);
			this._AspNetUsers = default(EntityRef<AspNetUsers>);
			this._GradoEscalafon1 = default(EntityRef<GradoEscalafon>);
			this._Cargo = default(EntityRef<Cargo>);
			this._Rol = default(EntityRef<Rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					if (this._AspNetUsers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUserChanging(value);
					this.SendPropertyChanging();
					this._IdUser = value;
					this.SendPropertyChanged("IdUser");
					this.OnIdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocumento", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string TipoDocumento
		{
			get
			{
				return this._TipoDocumento;
			}
			set
			{
				if ((this._TipoDocumento != value))
				{
					this.OnTipoDocumentoChanging(value);
					this.SendPropertyChanging();
					this._TipoDocumento = value;
					this.SendPropertyChanged("TipoDocumento");
					this.OnTipoDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Documento", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Documento
		{
			get
			{
				return this._Documento;
			}
			set
			{
				if ((this._Documento != value))
				{
					this.OnDocumentoChanging(value);
					this.SendPropertyChanging();
					this._Documento = value;
					this.SendPropertyChanged("Documento");
					this.OnDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDepartamentoExpedicion", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string CodDepartamentoExpedicion
		{
			get
			{
				return this._CodDepartamentoExpedicion;
			}
			set
			{
				if ((this._CodDepartamentoExpedicion != value))
				{
					this.OnCodDepartamentoExpedicionChanging(value);
					this.SendPropertyChanging();
					this._CodDepartamentoExpedicion = value;
					this.SendPropertyChanged("CodDepartamentoExpedicion");
					this.OnCodDepartamentoExpedicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodMunicipioExpedicion", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CodMunicipioExpedicion
		{
			get
			{
				return this._CodMunicipioExpedicion;
			}
			set
			{
				if ((this._CodMunicipioExpedicion != value))
				{
					this.OnCodMunicipioExpedicionChanging(value);
					this.SendPropertyChanging();
					this._CodMunicipioExpedicion = value;
					this.SendPropertyChanged("CodMunicipioExpedicion");
					this.OnCodMunicipioExpedicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PrimerNombre
		{
			get
			{
				return this._PrimerNombre;
			}
			set
			{
				if ((this._PrimerNombre != value))
				{
					this.OnPrimerNombreChanging(value);
					this.SendPropertyChanging();
					this._PrimerNombre = value;
					this.SendPropertyChanged("PrimerNombre");
					this.OnPrimerNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="VarChar(50)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this.OnSegundoNombreChanging(value);
					this.SendPropertyChanging();
					this._SegundoNombre = value;
					this.SendPropertyChanged("SegundoNombre");
					this.OnSegundoNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PrimerApellido
		{
			get
			{
				return this._PrimerApellido;
			}
			set
			{
				if ((this._PrimerApellido != value))
				{
					this.OnPrimerApellidoChanging(value);
					this.SendPropertyChanging();
					this._PrimerApellido = value;
					this.SendPropertyChanged("PrimerApellido");
					this.OnPrimerApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="VarChar(50)")]
		public string SegundoApellido
		{
			get
			{
				return this._SegundoApellido;
			}
			set
			{
				if ((this._SegundoApellido != value))
				{
					this.OnSegundoApellidoChanging(value);
					this.SendPropertyChanging();
					this._SegundoApellido = value;
					this.SendPropertyChanged("SegundoApellido");
					this.OnSegundoApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVinculacion", DbType="Date NOT NULL")]
		public System.DateTime FechaVinculacion
		{
			get
			{
				return this._FechaVinculacion;
			}
			set
			{
				if ((this._FechaVinculacion != value))
				{
					this.OnFechaVinculacionChanging(value);
					this.SendPropertyChanging();
					this._FechaVinculacion = value;
					this.SendPropertyChanged("FechaVinculacion");
					this.OnFechaVinculacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoVinculacion", DbType="Int NOT NULL")]
		public int IdTipoVinculacion
		{
			get
			{
				return this._IdTipoVinculacion;
			}
			set
			{
				if ((this._IdTipoVinculacion != value))
				{
					if (this._TipoVInculacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoVinculacionChanging(value);
					this.SendPropertyChanging();
					this._IdTipoVinculacion = value;
					this.SendPropertyChanged("IdTipoVinculacion");
					this.OnIdTipoVinculacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZonaAtender", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ZonaAtender
		{
			get
			{
				return this._ZonaAtender;
			}
			set
			{
				if ((this._ZonaAtender != value))
				{
					this.OnZonaAtenderChanging(value);
					this.SendPropertyChanging();
					this._ZonaAtender = value;
					this.SendPropertyChanged("ZonaAtender");
					this.OnZonaAtenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargoBase", DbType="Int NOT NULL")]
		public int CargoBase
		{
			get
			{
				return this._CargoBase;
			}
			set
			{
				if ((this._CargoBase != value))
				{
					if (this._Cargo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCargoBaseChanging(value);
					this.SendPropertyChanging();
					this._CargoBase = value;
					this.SendPropertyChanged("CargoBase");
					this.OnCargoBaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="NChar(10)")]
		public string Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this.OnNivelChanging(value);
					this.SendPropertyChanging();
					this._Nivel = value;
					this.SendPropertyChanged("Nivel");
					this.OnNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInstitucionEducativa", DbType="Int NOT NULL")]
		public int IdInstitucionEducativa
		{
			get
			{
				return this._IdInstitucionEducativa;
			}
			set
			{
				if ((this._IdInstitucionEducativa != value))
				{
					this.OnIdInstitucionEducativaChanging(value);
					this.SendPropertyChanging();
					this._IdInstitucionEducativa = value;
					this.SendPropertyChanged("IdInstitucionEducativa");
					this.OnIdInstitucionEducativaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSede", DbType="Int NOT NULL")]
		public int IdSede
		{
			get
			{
				return this._IdSede;
			}
			set
			{
				if ((this._IdSede != value))
				{
					this.OnIdSedeChanging(value);
					this.SendPropertyChanging();
					this._IdSede = value;
					this.SendPropertyChanged("IdSede");
					this.OnIdSedeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradoEscalafon", DbType="Int NOT NULL")]
		public int GradoEscalafon
		{
			get
			{
				return this._GradoEscalafon;
			}
			set
			{
				if ((this._GradoEscalafon != value))
				{
					if (this._GradoEscalafon1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGradoEscalafonChanging(value);
					this.SendPropertyChanging();
					this._GradoEscalafon = value;
					this.SendPropertyChanged("GradoEscalafon");
					this.OnGradoEscalafonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(50)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int NOT NULL")]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					if (this._Rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRolChanging(value);
					this.SendPropertyChanging();
					this._idRol = value;
					this.SendPropertyChanged("idRol");
					this.OnidRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="Date NOT NULL")]
		public System.DateTime FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoVInculacion_PerfilUsuario", Storage="_TipoVInculacion", ThisKey="IdTipoVinculacion", OtherKey="IdVinculacion", IsForeignKey=true)]
		public TipoVInculacion TipoVInculacion
		{
			get
			{
				return this._TipoVInculacion.Entity;
			}
			set
			{
				TipoVInculacion previousValue = this._TipoVInculacion.Entity;
				if (((previousValue != value) 
							|| (this._TipoVInculacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoVInculacion.Entity = null;
						previousValue.PerfilUsuario.Remove(this);
					}
					this._TipoVInculacion.Entity = value;
					if ((value != null))
					{
						value.PerfilUsuario.Add(this);
						this._IdTipoVinculacion = value.IdVinculacion;
					}
					else
					{
						this._IdTipoVinculacion = default(int);
					}
					this.SendPropertyChanged("TipoVInculacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AspNetUsers_PerfilUsuario", Storage="_AspNetUsers", ThisKey="IdUser", OtherKey="Id", IsForeignKey=true)]
		public AspNetUsers AspNetUsers
		{
			get
			{
				return this._AspNetUsers.Entity;
			}
			set
			{
				AspNetUsers previousValue = this._AspNetUsers.Entity;
				if (((previousValue != value) 
							|| (this._AspNetUsers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AspNetUsers.Entity = null;
						previousValue.PerfilUsuario.Remove(this);
					}
					this._AspNetUsers.Entity = value;
					if ((value != null))
					{
						value.PerfilUsuario.Add(this);
						this._IdUser = value.Id;
					}
					else
					{
						this._IdUser = default(string);
					}
					this.SendPropertyChanged("AspNetUsers");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GradoEscalafon_PerfilUsuario", Storage="_GradoEscalafon1", ThisKey="GradoEscalafon", OtherKey="Id", IsForeignKey=true)]
		public GradoEscalafon GradoEscalafon1
		{
			get
			{
				return this._GradoEscalafon1.Entity;
			}
			set
			{
				GradoEscalafon previousValue = this._GradoEscalafon1.Entity;
				if (((previousValue != value) 
							|| (this._GradoEscalafon1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GradoEscalafon1.Entity = null;
						previousValue.PerfilUsuario.Remove(this);
					}
					this._GradoEscalafon1.Entity = value;
					if ((value != null))
					{
						value.PerfilUsuario.Add(this);
						this._GradoEscalafon = value.Id;
					}
					else
					{
						this._GradoEscalafon = default(int);
					}
					this.SendPropertyChanged("GradoEscalafon1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cargo_PerfilUsuario", Storage="_Cargo", ThisKey="CargoBase", OtherKey="Id", IsForeignKey=true)]
		public Cargo Cargo
		{
			get
			{
				return this._Cargo.Entity;
			}
			set
			{
				Cargo previousValue = this._Cargo.Entity;
				if (((previousValue != value) 
							|| (this._Cargo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cargo.Entity = null;
						previousValue.PerfilUsuario.Remove(this);
					}
					this._Cargo.Entity = value;
					if ((value != null))
					{
						value.PerfilUsuario.Add(this);
						this._CargoBase = value.Id;
					}
					else
					{
						this._CargoBase = default(int);
					}
					this.SendPropertyChanged("Cargo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_PerfilUsuario", Storage="_Rol", ThisKey="idRol", OtherKey="Id", IsForeignKey=true)]
		public Rol Rol
		{
			get
			{
				return this._Rol.Entity;
			}
			set
			{
				Rol previousValue = this._Rol.Entity;
				if (((previousValue != value) 
							|| (this._Rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol.Entity = null;
						previousValue.PerfilUsuario.Remove(this);
					}
					this._Rol.Entity = value;
					if ((value != null))
					{
						value.PerfilUsuario.Add(this);
						this._idRol = value.Id;
					}
					else
					{
						this._idRol = default(int);
					}
					this.SendPropertyChanged("Rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AreaDesempeno")]
	public partial class AreaDesempeno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public AreaDesempeno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RegistroAreaDesempeno")]
	public partial class RegistroAreaDesempeno
	{
		
		private string _IdUsuario;
		
		private int _IdAreaDesempeno;
		
		public RegistroAreaDesempeno()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAreaDesempeno", DbType="Int NOT NULL")]
		public int IdAreaDesempeno
		{
			get
			{
				return this._IdAreaDesempeno;
			}
			set
			{
				if ((this._IdAreaDesempeno != value))
				{
					this._IdAreaDesempeno = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RecuperacionContrasena")]
	public partial class RecuperacionContrasena : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _idUser;
		
		private string _Token;
		
		private System.DateTime _Vencimiento;
		
		private EntityRef<AspNetUsers> _AspNetUsers;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidUserChanging(string value);
    partial void OnidUserChanged();
    partial void OnTokenChanging(string value);
    partial void OnTokenChanged();
    partial void OnVencimientoChanging(System.DateTime value);
    partial void OnVencimientoChanged();
    #endregion
		
		public RecuperacionContrasena()
		{
			this._AspNetUsers = default(EntityRef<AspNetUsers>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					if (this._AspNetUsers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUserChanging(value);
					this.SendPropertyChanging();
					this._idUser = value;
					this.SendPropertyChanged("idUser");
					this.OnidUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Token", DbType="NVarChar(258) NOT NULL", CanBeNull=false)]
		public string Token
		{
			get
			{
				return this._Token;
			}
			set
			{
				if ((this._Token != value))
				{
					this.OnTokenChanging(value);
					this.SendPropertyChanging();
					this._Token = value;
					this.SendPropertyChanged("Token");
					this.OnTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vencimiento", DbType="DateTime NOT NULL")]
		public System.DateTime Vencimiento
		{
			get
			{
				return this._Vencimiento;
			}
			set
			{
				if ((this._Vencimiento != value))
				{
					this.OnVencimientoChanging(value);
					this.SendPropertyChanging();
					this._Vencimiento = value;
					this.SendPropertyChanged("Vencimiento");
					this.OnVencimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AspNetUsers_RecuperacionContrasena", Storage="_AspNetUsers", ThisKey="idUser", OtherKey="Id", IsForeignKey=true)]
		public AspNetUsers AspNetUsers
		{
			get
			{
				return this._AspNetUsers.Entity;
			}
			set
			{
				AspNetUsers previousValue = this._AspNetUsers.Entity;
				if (((previousValue != value) 
							|| (this._AspNetUsers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AspNetUsers.Entity = null;
						previousValue.RecuperacionContrasena.Remove(this);
					}
					this._AspNetUsers.Entity = value;
					if ((value != null))
					{
						value.RecuperacionContrasena.Add(this);
						this._idUser = value.Id;
					}
					else
					{
						this._idUser = default(string);
					}
					this.SendPropertyChanged("AspNetUsers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
