#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEducativo.Models.Configuracion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PIAR")]
	public partial class ConfiguracionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertRol(Rol instance);
    partial void UpdateRol(Rol instance);
    partial void DeleteRol(Rol instance);
    partial void InsertSede(Sede instance);
    partial void UpdateSede(Sede instance);
    partial void DeleteSede(Sede instance);
    partial void InsertPerfilUsuario(PerfilUsuario instance);
    partial void UpdatePerfilUsuario(PerfilUsuario instance);
    partial void DeletePerfilUsuario(PerfilUsuario instance);
    partial void InsertInstitucionEducativa(InstitucionEducativa instance);
    partial void UpdateInstitucionEducativa(InstitucionEducativa instance);
    partial void DeleteInstitucionEducativa(InstitucionEducativa instance);
    partial void InsertTipoVInculacion(TipoVInculacion instance);
    partial void UpdateTipoVInculacion(TipoVInculacion instance);
    partial void DeleteTipoVInculacion(TipoVInculacion instance);
    #endregion
		
		public ConfiguracionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PIARConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfiguracionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Rol> Rol
		{
			get
			{
				return this.GetTable<Rol>();
			}
		}
		
		public System.Data.Linq.Table<Sede> Sede
		{
			get
			{
				return this.GetTable<Sede>();
			}
		}
		
		public System.Data.Linq.Table<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this.GetTable<PerfilUsuario>();
			}
		}
		
		public System.Data.Linq.Table<InstitucionEducativa> InstitucionEducativa
		{
			get
			{
				return this.GetTable<InstitucionEducativa>();
			}
		}
		
		public System.Data.Linq.Table<TipoVInculacion> TipoVInculacion
		{
			get
			{
				return this.GetTable<TipoVInculacion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
	public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NombreRol;
		
		private bool _Eliminado;
		
		private EntitySet<PerfilUsuario> _PerfilUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreRolChanging(string value);
    partial void OnNombreRolChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public Rol()
		{
			this._PerfilUsuario = new EntitySet<PerfilUsuario>(new Action<PerfilUsuario>(this.attach_PerfilUsuario), new Action<PerfilUsuario>(this.detach_PerfilUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreRol", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string NombreRol
		{
			get
			{
				return this._NombreRol;
			}
			set
			{
				if ((this._NombreRol != value))
				{
					this.OnNombreRolChanging(value);
					this.SendPropertyChanging();
					this._NombreRol = value;
					this.SendPropertyChanged("NombreRol");
					this.OnNombreRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_PerfilUsuario", Storage="_PerfilUsuario", ThisKey="Id", OtherKey="idRol")]
		public EntitySet<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this._PerfilUsuario;
			}
			set
			{
				this._PerfilUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Rol = this;
		}
		
		private void detach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sede")]
	public partial class Sede : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private bool _Eliminado;
		
		private EntitySet<PerfilUsuario> _PerfilUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public Sede()
		{
			this._PerfilUsuario = new EntitySet<PerfilUsuario>(new Action<PerfilUsuario>(this.attach_PerfilUsuario), new Action<PerfilUsuario>(this.detach_PerfilUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sede_PerfilUsuario", Storage="_PerfilUsuario", ThisKey="Id", OtherKey="IdSede")]
		public EntitySet<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this._PerfilUsuario;
			}
			set
			{
				this._PerfilUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Sede = this;
		}
		
		private void detach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Sede = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PerfilUsuario")]
	public partial class PerfilUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _IdUser;
		
		private string _TipoDocumento;
		
		private string _Documento;
		
		private string _CodDepartamentoExpedicion;
		
		private string _CodMunicipioExpedicion;
		
		private string _PrimerNombre;
		
		private string _SegundoNombre;
		
		private string _PrimerApellido;
		
		private string _SegundoApellido;
		
		private System.DateTime _FechaNacimiento;
		
		private System.DateTime _FechaVinculacion;
		
		private int _IdTipoVinculacion;
		
		private string _ZonaAtender;
		
		private string _CargoBase;
		
		private string _Nivel;
		
		private string _AreaDesempeno;
		
		private int _IdInstitucionEducativa;
		
		private int _IdSede;
		
		private int _GradoEscalafon;
		
		private string _Titulo;
		
		private string _CorreoElectronico;
		
		private string _Contrasena;
		
		private int _idRol;
		
		private System.DateTime _FechaModificacion;
		
		private EntityRef<Rol> _Rol;
		
		private EntityRef<Sede> _Sede;
		
		private EntityRef<InstitucionEducativa> _InstitucionEducativa;
		
		private EntityRef<TipoVInculacion> _TipoVInculacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnIdUserChanging(string value);
    partial void OnIdUserChanged();
    partial void OnTipoDocumentoChanging(string value);
    partial void OnTipoDocumentoChanged();
    partial void OnDocumentoChanging(string value);
    partial void OnDocumentoChanged();
    partial void OnCodDepartamentoExpedicionChanging(string value);
    partial void OnCodDepartamentoExpedicionChanged();
    partial void OnCodMunicipioExpedicionChanging(string value);
    partial void OnCodMunicipioExpedicionChanged();
    partial void OnPrimerNombreChanging(string value);
    partial void OnPrimerNombreChanged();
    partial void OnSegundoNombreChanging(string value);
    partial void OnSegundoNombreChanged();
    partial void OnPrimerApellidoChanging(string value);
    partial void OnPrimerApellidoChanged();
    partial void OnSegundoApellidoChanging(string value);
    partial void OnSegundoApellidoChanged();
    partial void OnFechaNacimientoChanging(System.DateTime value);
    partial void OnFechaNacimientoChanged();
    partial void OnFechaVinculacionChanging(System.DateTime value);
    partial void OnFechaVinculacionChanged();
    partial void OnIdTipoVinculacionChanging(int value);
    partial void OnIdTipoVinculacionChanged();
    partial void OnZonaAtenderChanging(string value);
    partial void OnZonaAtenderChanged();
    partial void OnCargoBaseChanging(string value);
    partial void OnCargoBaseChanged();
    partial void OnNivelChanging(string value);
    partial void OnNivelChanged();
    partial void OnAreaDesempenoChanging(string value);
    partial void OnAreaDesempenoChanged();
    partial void OnIdInstitucionEducativaChanging(int value);
    partial void OnIdInstitucionEducativaChanged();
    partial void OnIdSedeChanging(int value);
    partial void OnIdSedeChanged();
    partial void OnGradoEscalafonChanging(int value);
    partial void OnGradoEscalafonChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnCorreoElectronicoChanging(string value);
    partial void OnCorreoElectronicoChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnidRolChanging(int value);
    partial void OnidRolChanged();
    partial void OnFechaModificacionChanging(System.DateTime value);
    partial void OnFechaModificacionChanged();
    #endregion
		
		public PerfilUsuario()
		{
			this._Rol = default(EntityRef<Rol>);
			this._Sede = default(EntityRef<Sede>);
			this._InstitucionEducativa = default(EntityRef<InstitucionEducativa>);
			this._TipoVInculacion = default(EntityRef<TipoVInculacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					this.OnIdUserChanging(value);
					this.SendPropertyChanging();
					this._IdUser = value;
					this.SendPropertyChanged("IdUser");
					this.OnIdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocumento", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string TipoDocumento
		{
			get
			{
				return this._TipoDocumento;
			}
			set
			{
				if ((this._TipoDocumento != value))
				{
					this.OnTipoDocumentoChanging(value);
					this.SendPropertyChanging();
					this._TipoDocumento = value;
					this.SendPropertyChanged("TipoDocumento");
					this.OnTipoDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Documento", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Documento
		{
			get
			{
				return this._Documento;
			}
			set
			{
				if ((this._Documento != value))
				{
					this.OnDocumentoChanging(value);
					this.SendPropertyChanging();
					this._Documento = value;
					this.SendPropertyChanged("Documento");
					this.OnDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDepartamentoExpedicion", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string CodDepartamentoExpedicion
		{
			get
			{
				return this._CodDepartamentoExpedicion;
			}
			set
			{
				if ((this._CodDepartamentoExpedicion != value))
				{
					this.OnCodDepartamentoExpedicionChanging(value);
					this.SendPropertyChanging();
					this._CodDepartamentoExpedicion = value;
					this.SendPropertyChanged("CodDepartamentoExpedicion");
					this.OnCodDepartamentoExpedicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodMunicipioExpedicion", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CodMunicipioExpedicion
		{
			get
			{
				return this._CodMunicipioExpedicion;
			}
			set
			{
				if ((this._CodMunicipioExpedicion != value))
				{
					this.OnCodMunicipioExpedicionChanging(value);
					this.SendPropertyChanging();
					this._CodMunicipioExpedicion = value;
					this.SendPropertyChanged("CodMunicipioExpedicion");
					this.OnCodMunicipioExpedicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PrimerNombre
		{
			get
			{
				return this._PrimerNombre;
			}
			set
			{
				if ((this._PrimerNombre != value))
				{
					this.OnPrimerNombreChanging(value);
					this.SendPropertyChanging();
					this._PrimerNombre = value;
					this.SendPropertyChanged("PrimerNombre");
					this.OnPrimerNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="VarChar(50)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this.OnSegundoNombreChanging(value);
					this.SendPropertyChanging();
					this._SegundoNombre = value;
					this.SendPropertyChanged("SegundoNombre");
					this.OnSegundoNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PrimerApellido
		{
			get
			{
				return this._PrimerApellido;
			}
			set
			{
				if ((this._PrimerApellido != value))
				{
					this.OnPrimerApellidoChanging(value);
					this.SendPropertyChanging();
					this._PrimerApellido = value;
					this.SendPropertyChanged("PrimerApellido");
					this.OnPrimerApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="VarChar(50)")]
		public string SegundoApellido
		{
			get
			{
				return this._SegundoApellido;
			}
			set
			{
				if ((this._SegundoApellido != value))
				{
					this.OnSegundoApellidoChanging(value);
					this.SendPropertyChanging();
					this._SegundoApellido = value;
					this.SendPropertyChanged("SegundoApellido");
					this.OnSegundoApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVinculacion", DbType="Date NOT NULL")]
		public System.DateTime FechaVinculacion
		{
			get
			{
				return this._FechaVinculacion;
			}
			set
			{
				if ((this._FechaVinculacion != value))
				{
					this.OnFechaVinculacionChanging(value);
					this.SendPropertyChanging();
					this._FechaVinculacion = value;
					this.SendPropertyChanged("FechaVinculacion");
					this.OnFechaVinculacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoVinculacion", DbType="Int NOT NULL")]
		public int IdTipoVinculacion
		{
			get
			{
				return this._IdTipoVinculacion;
			}
			set
			{
				if ((this._IdTipoVinculacion != value))
				{
					if (this._TipoVInculacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoVinculacionChanging(value);
					this.SendPropertyChanging();
					this._IdTipoVinculacion = value;
					this.SendPropertyChanged("IdTipoVinculacion");
					this.OnIdTipoVinculacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZonaAtender", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ZonaAtender
		{
			get
			{
				return this._ZonaAtender;
			}
			set
			{
				if ((this._ZonaAtender != value))
				{
					this.OnZonaAtenderChanging(value);
					this.SendPropertyChanging();
					this._ZonaAtender = value;
					this.SendPropertyChanged("ZonaAtender");
					this.OnZonaAtenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargoBase", DbType="VarChar(50)")]
		public string CargoBase
		{
			get
			{
				return this._CargoBase;
			}
			set
			{
				if ((this._CargoBase != value))
				{
					this.OnCargoBaseChanging(value);
					this.SendPropertyChanging();
					this._CargoBase = value;
					this.SendPropertyChanged("CargoBase");
					this.OnCargoBaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="NChar(10)")]
		public string Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this.OnNivelChanging(value);
					this.SendPropertyChanging();
					this._Nivel = value;
					this.SendPropertyChanged("Nivel");
					this.OnNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaDesempeno", DbType="VarChar(50)")]
		public string AreaDesempeno
		{
			get
			{
				return this._AreaDesempeno;
			}
			set
			{
				if ((this._AreaDesempeno != value))
				{
					this.OnAreaDesempenoChanging(value);
					this.SendPropertyChanging();
					this._AreaDesempeno = value;
					this.SendPropertyChanged("AreaDesempeno");
					this.OnAreaDesempenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInstitucionEducativa", DbType="Int NOT NULL")]
		public int IdInstitucionEducativa
		{
			get
			{
				return this._IdInstitucionEducativa;
			}
			set
			{
				if ((this._IdInstitucionEducativa != value))
				{
					if (this._InstitucionEducativa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdInstitucionEducativaChanging(value);
					this.SendPropertyChanging();
					this._IdInstitucionEducativa = value;
					this.SendPropertyChanged("IdInstitucionEducativa");
					this.OnIdInstitucionEducativaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSede", DbType="Int NOT NULL")]
		public int IdSede
		{
			get
			{
				return this._IdSede;
			}
			set
			{
				if ((this._IdSede != value))
				{
					if (this._Sede.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSedeChanging(value);
					this.SendPropertyChanging();
					this._IdSede = value;
					this.SendPropertyChanged("IdSede");
					this.OnIdSedeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradoEscalafon", DbType="Int NOT NULL")]
		public int GradoEscalafon
		{
			get
			{
				return this._GradoEscalafon;
			}
			set
			{
				if ((this._GradoEscalafon != value))
				{
					this.OnGradoEscalafonChanging(value);
					this.SendPropertyChanging();
					this._GradoEscalafon = value;
					this.SendPropertyChanged("GradoEscalafon");
					this.OnGradoEscalafonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(50)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this.OnCorreoElectronicoChanging(value);
					this.SendPropertyChanging();
					this._CorreoElectronico = value;
					this.SendPropertyChanged("CorreoElectronico");
					this.OnCorreoElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int NOT NULL")]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					if (this._Rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRolChanging(value);
					this.SendPropertyChanging();
					this._idRol = value;
					this.SendPropertyChanged("idRol");
					this.OnidRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="Date NOT NULL")]
		public System.DateTime FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_PerfilUsuario", Storage="_Rol", ThisKey="idRol", OtherKey="Id", IsForeignKey=true)]
		public Rol Rol
		{
			get
			{
				return this._Rol.Entity;
			}
			set
			{
				Rol previousValue = this._Rol.Entity;
				if (((previousValue != value) 
							|| (this._Rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol.Entity = null;
						previousValue.PerfilUsuario.Remove(this);
					}
					this._Rol.Entity = value;
					if ((value != null))
					{
						value.PerfilUsuario.Add(this);
						this._idRol = value.Id;
					}
					else
					{
						this._idRol = default(int);
					}
					this.SendPropertyChanged("Rol");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sede_PerfilUsuario", Storage="_Sede", ThisKey="IdSede", OtherKey="Id", IsForeignKey=true)]
		public Sede Sede
		{
			get
			{
				return this._Sede.Entity;
			}
			set
			{
				Sede previousValue = this._Sede.Entity;
				if (((previousValue != value) 
							|| (this._Sede.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sede.Entity = null;
						previousValue.PerfilUsuario.Remove(this);
					}
					this._Sede.Entity = value;
					if ((value != null))
					{
						value.PerfilUsuario.Add(this);
						this._IdSede = value.Id;
					}
					else
					{
						this._IdSede = default(int);
					}
					this.SendPropertyChanged("Sede");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="InstitucionEducativa_PerfilUsuario", Storage="_InstitucionEducativa", ThisKey="IdInstitucionEducativa", OtherKey="Id", IsForeignKey=true)]
		public InstitucionEducativa InstitucionEducativa
		{
			get
			{
				return this._InstitucionEducativa.Entity;
			}
			set
			{
				InstitucionEducativa previousValue = this._InstitucionEducativa.Entity;
				if (((previousValue != value) 
							|| (this._InstitucionEducativa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._InstitucionEducativa.Entity = null;
						previousValue.PerfilUsuario.Remove(this);
					}
					this._InstitucionEducativa.Entity = value;
					if ((value != null))
					{
						value.PerfilUsuario.Add(this);
						this._IdInstitucionEducativa = value.Id;
					}
					else
					{
						this._IdInstitucionEducativa = default(int);
					}
					this.SendPropertyChanged("InstitucionEducativa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoVInculacion_PerfilUsuario", Storage="_TipoVInculacion", ThisKey="IdTipoVinculacion", OtherKey="IdVinculacion", IsForeignKey=true)]
		public TipoVInculacion TipoVInculacion
		{
			get
			{
				return this._TipoVInculacion.Entity;
			}
			set
			{
				TipoVInculacion previousValue = this._TipoVInculacion.Entity;
				if (((previousValue != value) 
							|| (this._TipoVInculacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoVInculacion.Entity = null;
						previousValue.PerfilUsuario.Remove(this);
					}
					this._TipoVInculacion.Entity = value;
					if ((value != null))
					{
						value.PerfilUsuario.Add(this);
						this._IdTipoVinculacion = value.IdVinculacion;
					}
					else
					{
						this._IdTipoVinculacion = default(int);
					}
					this.SendPropertyChanged("TipoVInculacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InstitucionEducativa")]
	public partial class InstitucionEducativa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NombreInstitucion;
		
		private bool _Eliminado;
		
		private EntitySet<PerfilUsuario> _PerfilUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreInstitucionChanging(string value);
    partial void OnNombreInstitucionChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public InstitucionEducativa()
		{
			this._PerfilUsuario = new EntitySet<PerfilUsuario>(new Action<PerfilUsuario>(this.attach_PerfilUsuario), new Action<PerfilUsuario>(this.detach_PerfilUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreInstitucion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreInstitucion
		{
			get
			{
				return this._NombreInstitucion;
			}
			set
			{
				if ((this._NombreInstitucion != value))
				{
					this.OnNombreInstitucionChanging(value);
					this.SendPropertyChanging();
					this._NombreInstitucion = value;
					this.SendPropertyChanged("NombreInstitucion");
					this.OnNombreInstitucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="InstitucionEducativa_PerfilUsuario", Storage="_PerfilUsuario", ThisKey="Id", OtherKey="IdInstitucionEducativa")]
		public EntitySet<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this._PerfilUsuario;
			}
			set
			{
				this._PerfilUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.InstitucionEducativa = this;
		}
		
		private void detach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.InstitucionEducativa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoVInculacion")]
	public partial class TipoVInculacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVinculacion;
		
		private string _TipoVinculacion1;
		
		private EntitySet<PerfilUsuario> _PerfilUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVinculacionChanging(int value);
    partial void OnIdVinculacionChanged();
    partial void OnTipoVinculacion1Changing(string value);
    partial void OnTipoVinculacion1Changed();
    #endregion
		
		public TipoVInculacion()
		{
			this._PerfilUsuario = new EntitySet<PerfilUsuario>(new Action<PerfilUsuario>(this.attach_PerfilUsuario), new Action<PerfilUsuario>(this.detach_PerfilUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVinculacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVinculacion
		{
			get
			{
				return this._IdVinculacion;
			}
			set
			{
				if ((this._IdVinculacion != value))
				{
					this.OnIdVinculacionChanging(value);
					this.SendPropertyChanging();
					this._IdVinculacion = value;
					this.SendPropertyChanged("IdVinculacion");
					this.OnIdVinculacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TipoVinculacion", Storage="_TipoVinculacion1", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TipoVinculacion1
		{
			get
			{
				return this._TipoVinculacion1;
			}
			set
			{
				if ((this._TipoVinculacion1 != value))
				{
					this.OnTipoVinculacion1Changing(value);
					this.SendPropertyChanging();
					this._TipoVinculacion1 = value;
					this.SendPropertyChanged("TipoVinculacion1");
					this.OnTipoVinculacion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoVInculacion_PerfilUsuario", Storage="_PerfilUsuario", ThisKey="IdVinculacion", OtherKey="IdTipoVinculacion")]
		public EntitySet<PerfilUsuario> PerfilUsuario
		{
			get
			{
				return this._PerfilUsuario;
			}
			set
			{
				this._PerfilUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.TipoVInculacion = this;
		}
		
		private void detach_PerfilUsuario(PerfilUsuario entity)
		{
			this.SendPropertyChanging();
			entity.TipoVInculacion = null;
		}
	}
}
#pragma warning restore 1591
