<?xml version="1.0" encoding="utf-8"?><Database Name="PIAR" Class="ConfiguracionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ESCRITORIO-CARL\SQLSERVEREXPRESS;Initial Catalog=PIAR;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PIARConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Rol" Member="Rol">
    <Type Name="Rol">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreRol" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Eliminado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Rol_PerfilUsuario" Member="PerfilUsuario" ThisKey="Id" OtherKey="idRol" Type="PerfilUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.TipoVInculacion" Member="TipoVInculacion">
    <Type Name="TipoVInculacion">
      <Column Name="IdVinculacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoVinculacion" Member="TipoVinculacion1" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="TipoVInculacion_PerfilUsuario" Member="PerfilUsuario" ThisKey="IdVinculacion" OtherKey="IdTipoVinculacion" Type="PerfilUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUsers">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUsers_PerfilUsuario" Member="PerfilUsuario" ThisKey="Id" OtherKey="IdUser" Type="PerfilUsuario" />
      <Association Name="AspNetUsers_RegistroAreaDesempeno" Member="RegistroAreaDesempeno" ThisKey="Id" OtherKey="IdUsuario" Type="RegistroAreaDesempeno" />
      <Association Name="AspNetUsers_RecuperacionContrasena" Member="RecuperacionContrasena" ThisKey="Id" OtherKey="idUser" Type="RecuperacionContrasena" />
    </Type>
  </Table>
  <Table Name="dbo.Cargo" Member="Cargo">
    <Type Name="Cargo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Cargo_PerfilUsuario" Member="PerfilUsuario" ThisKey="Id" OtherKey="CargoBase" Type="PerfilUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.GradoEscalafon" Member="GradoEscalafon">
    <Type Name="GradoEscalafon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Association Name="GradoEscalafon_PerfilUsuario" Member="PerfilUsuario" ThisKey="Id" OtherKey="GradoEscalafon" Type="PerfilUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.PerfilUsuario" Member="PerfilUsuario">
    <Type Name="PerfilUsuario">
      <Column Name="id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdUser" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TipoDocumento" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Documento" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CodDepartamentoExpedicion" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CodMunicipioExpedicion" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrimerApellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FechaVinculacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoVinculacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZonaAtender" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CargoBase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nivel" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IdInstitucionEducativa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdSede" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradoEscalafon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FechaModificacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Eliminado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TipoVInculacion_PerfilUsuario" Member="TipoVInculacion" ThisKey="IdTipoVinculacion" OtherKey="IdVinculacion" Type="TipoVInculacion" IsForeignKey="true" />
      <Association Name="AspNetUsers_PerfilUsuario" Member="AspNetUsers" ThisKey="IdUser" OtherKey="Id" Type="AspNetUsers" IsForeignKey="true" />
      <Association Name="GradoEscalafon_PerfilUsuario" Member="GradoEscalafon1" ThisKey="GradoEscalafon" OtherKey="Id" Type="GradoEscalafon" IsForeignKey="true" />
      <Association Name="Cargo_PerfilUsuario" Member="Cargo" ThisKey="CargoBase" OtherKey="Id" Type="Cargo" IsForeignKey="true" />
      <Association Name="Rol_PerfilUsuario" Member="Rol" ThisKey="idRol" OtherKey="Id" Type="Rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AreaDesempeno" Member="AreaDesempeno">
    <Type Name="AreaDesempeno">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="AreaDesempeno_RegistroAreaDesempeno" Member="RegistroAreaDesempeno" ThisKey="Id" OtherKey="IdAreaDesempeno" Type="RegistroAreaDesempeno" />
    </Type>
  </Table>
  <Table Name="dbo.RegistroAreaDesempeno" Member="RegistroAreaDesempeno">
    <Type Name="RegistroAreaDesempeno">
      <Column Name="IdUsuario" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="IdAreaDesempeno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AreaDesempeno_RegistroAreaDesempeno" Member="AreaDesempeno" ThisKey="IdAreaDesempeno" OtherKey="Id" Type="AreaDesempeno" IsForeignKey="true" />
      <Association Name="AspNetUsers_RegistroAreaDesempeno" Member="AspNetUsers" ThisKey="IdUsuario" OtherKey="Id" Type="AspNetUsers" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RecuperacionContrasena" Member="RecuperacionContrasena">
    <Type Name="RecuperacionContrasena">
      <Column Name="id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(258) NOT NULL" CanBeNull="false" />
      <Column Name="Vencimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUsers_RecuperacionContrasena" Member="AspNetUsers" ThisKey="idUser" OtherKey="Id" Type="AspNetUsers" IsForeignKey="true" />
    </Type>
  </Table>
</Database>